// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c32b11589f2bc68b "humanpass", do not edit manually */
"use client";

// virtual:connection-card-item
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'No badge' // Variant
 * rightText?: string // rightText
 * title?: string // title
 * subtitle?: string // subtitle
 * image?: {src: string, srcSet?: string, alt?: string} // image
 * badgeImage?: {src: string, srcSet?: string, alt?: string} // badgeImage
}} Props

 */
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qRSsXkPO9PwwwsnHSwNs/5iTxlwATVY1myumfTEav/V81cUXVhy.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCodeBoundaryForOverrides,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/1oMTLy48mQlkHUIQamxl/LQz0SsKx4UpdYoEs5F0b/TextGlitch.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useEffect, useRef, useState } from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
var DEFAULT_SCRAMBLE_CHARS =
	"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?";
function TextGlitch(props) {
	const { text, font, color, scrambleColor, duration, style, glitch } = props;
	const [display, setDisplay] = useState(text);
	const [scrambling, setScrambling] = useState(false);
	const intervalRef = useRef(null);
	const timeoutRef = useRef(null);
	const chars = (props.scrambleChars || DEFAULT_SCRAMBLE_CHARS).split("");
	useEffect(() => {
		if (!glitch) {
			setDisplay(text);
			setScrambling(false);
			return;
		}
		if (RenderTarget.current() !== RenderTarget.preview) {
			setDisplay(text);
			setScrambling(false);
			return;
		}
		if (RenderTarget.current() === RenderTarget.thumbnail) {
			setDisplay(text);
			setScrambling(false);
			return;
		}
		setDisplay(text);
		setScrambling(true);
		let frame = 0;
		const scramble = () => {
			const percent = Math.max(0, Math.min(100, props.scramblePercent ?? 100));
			let scrambled = text
				.split("")
				.map((c, i) => {
					if (c === " ") return c;
					if (Math.random() * 100 > percent) return c;
					return `<span data-scramble="1">${chars[Math.floor(Math.random() * chars.length)]}</span>`;
				})
				.join("");
			setDisplay(scrambled);
			frame++;
		};
		intervalRef.current = window.setInterval(scramble, props.speed || 40);
		timeoutRef.current = window.setTimeout(() => {
			if (intervalRef.current) clearInterval(intervalRef.current);
			setDisplay(text);
			setScrambling(false);
		}, duration);
		return () => {
			if (intervalRef.current) clearInterval(intervalRef.current);
			if (timeoutRef.current) clearTimeout(timeoutRef.current);
		};
	}, [text, duration, glitch, props.scrambleChars]);
	function renderText() {
		const { weight, optical } = props.variable || {
			weight: 400,
			optical: 22,
		};
		const fontVariation = {
			fontWeight: weight,
			fontVariationSettings: `'wght' ${weight}, 'opsz' ${optical}`,
		};
		const styleBase = {
			...font,
			color,
			...fontVariation,
		};
		if (!scrambling) return <span style={styleBase}>{text}</span>;
		const parts = display.split(/(<span data-scramble="1">.*?<\/span>)/g);
		return (
			<span style={styleBase}>
				{parts.map((part, i) => {
					if (part.startsWith('<span data-scramble="1">')) {
						const letter = part.replace(/<.*?>/g, "");
						return (
							<span
								style={{
									color: scrambleColor,
								}}
							>
								{letter}
							</span>
						);
					}
					return <span>{part}</span>;
				})}
			</span>
		);
	}
	const isFixedWidth = style && style.width === "100%";
	const isFixedHeight = style && style.height === "100%";
	return (
		<div
			style={{
				...style,
				position: "relative",
				width: isFixedWidth ? "100%" : "max-content",
				minWidth: isFixedWidth ? void 0 : "max-content",
				height: isFixedHeight ? "100%" : void 0,
			}}
		>
			{renderText()}
		</div>
	);
}
TextGlitch.displayName = "Text Glitch";
addPropertyControls(TextGlitch, {
	text: {
		type: ControlType.String,
		title: "Text",
		defaultValue: "Scramble Me!",
	},
	font: {
		type: ControlType.Font,
		title: "Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: 22,
			variant: "Semibold",
			letterSpacing: "-0.01em",
			lineHeight: "1.2em",
		},
	},
	variable: {
		type: ControlType.Object,
		title: "Variable",
		controls: {
			optical: {
				type: ControlType.Number,
				title: "Optical",
				defaultValue: 22,
				min: 14,
				max: 32,
				step: 1,
			},
			weight: {
				type: ControlType.Number,
				title: "Weight",
				defaultValue: 400,
				min: 100,
				max: 900,
				step: 1,
			},
		},
		defaultValue: {
			optical: 22,
			weight: 400,
		},
	},
	color: {
		type: ControlType.Color,
		title: "Color",
		defaultValue: "#000000",
	},
	scrambleColor: {
		type: ControlType.Color,
		title: "Scrambled",
		defaultValue: "#8855FF",
	},
	scrambleChars: {
		// <-- Add the control
		type: ControlType.String,
		title: "Chars",
		defaultValue: DEFAULT_SCRAMBLE_CHARS,
		displayTextArea: true,
	},
	scramblePercent: {
		type: ControlType.Number,
		title: "Scramble %",
		defaultValue: 100,
		min: 0,
		max: 100,
		unit: "%",
		step: 1,
	},
	speed: {
		type: ControlType.Number,
		title: "Speed",
		defaultValue: 40,
		min: 10,
		max: 200,
		unit: "ms",
		step: 1,
	},
	duration: {
		type: ControlType.Number,
		title: "Duration",
		defaultValue: 1200,
		min: 200,
		max: 5e3,
		unit: "ms",
		step: 50,
	},
	glitch: {
		type: ControlType.Boolean,
		title: "Glitch",
		enabledTitle: "Yes",
		disabledTitle: "No",
		defaultValue: true,
	},
});

// /:https://framerusercontent.com/modules/nDVghySNPhDaH5MOstwi/zlSWYZhAfkLti4Yciw5Z/TextTruncate.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import { forwardRef } from "react";
function withTruncateOneLine(Component2) {
	return /* @__PURE__ */ forwardRef((props, ref) => {
		const truncateStyle = {
			display: "-webkit-box",
			WebkitLineClamp: 1,
			WebkitBoxOrient: "vertical",
			overflow: "hidden",
			textOverflow: "ellipsis",
			...props.style,
		};
		return <Component2 ref={ref} {...props} style={truncateStyle} />;
	});
}

// /:https://framerusercontent.com/modules/98ORxWqlwYbJSprEgxIC/flBGuhQnA9EJbbUQJTgQ/sQrIs9_t0.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"BI;Raveo Variable/variable/v0",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
]);
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Raveo Variable",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
				variationAxes,
				weight: "1000",
			},
		],
	},
];
var css = [
	'.framer-D0GFO .framer-styles-preset-ujo3da:not(.rich-text-wrapper), .framer-D0GFO .framer-styles-preset-ujo3da.rich-text-wrapper p { --framer-font-family: "Raveo Variable Variable", sans-serif; --framer-font-family-bold: "Raveo Variable Variable", sans-serif; --framer-font-family-bold-italic: "Raveo Variable Variable", sans-serif; --framer-font-family-italic: "Raveo Variable Variable", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: normal; --framer-font-style-italic: normal; --framer-font-variation-axes: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold-italic: "opsz" 14, "wght" 550; --framer-font-variation-axes-italic: "opsz" 14, "wght" 550; --framer-font-weight: 1000; --framer-font-weight-bold: 1000; --framer-font-weight-bold-italic: 1000; --framer-font-weight-italic: 1000; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className = "framer-D0GFO";

// /:https://framerusercontent.com/modules/Asle8jS96yaopu1a0AVj/MHUz3hu8LPvKEbP3fwXZ/Xa6VJQy2p.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"BI;Raveo Variable/variable/v0",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNDUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNDUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNDUw",
]);
var variationAxes2 = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Raveo Variable",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
				variationAxes: variationAxes2,
				weight: "1000",
			},
		],
	},
];
var css2 = [
	'.framer-Vac31 .framer-styles-preset-c9mga6:not(.rich-text-wrapper), .framer-Vac31 .framer-styles-preset-c9mga6.rich-text-wrapper p { --framer-font-family: "Raveo Variable Variable", sans-serif; --framer-font-family-bold: "Raveo Variable Variable", sans-serif; --framer-font-family-bold-italic: "Raveo Variable Variable", sans-serif; --framer-font-family-italic: "Raveo Variable Variable", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: normal; --framer-font-style-italic: normal; --framer-font-variation-axes: "opsz" 14, "wght" 450; --framer-font-variation-axes-bold: "opsz" 14, "wght" 450; --framer-font-variation-axes-bold-italic: "opsz" 14, "wght" 450; --framer-font-variation-axes-italic: "opsz" 14, "wght" 450; --framer-font-weight: 1000; --framer-font-weight-bold: 1000; --framer-font-weight-bold-italic: 1000; --framer-font-weight-italic: 1000; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className2 = "framer-Vac31";

// /:https://framerusercontent.com/modules/qRSsXkPO9PwwwsnHSwNs/5iTxlwATVY1myumfTEav/V81cUXVhy.js
var RichTextWithTruncateOneLine1hvb3yo = withCodeBoundaryForOverrides(
	RichText,
	{
		nodeId: "ZkeT9tcCl",
		override: withTruncateOneLine,
		scopeId: "V81cUXVhy",
	},
);
var TextGlitchFonts = getFonts(TextGlitch);
var cycleOrder = ["NxSFvNIQD", "JLjMs0za_"];
var serializationHash = "framer-m1TdF";
var variantClassNames = {
	JLjMs0za_: "framer-v-1qomsu8",
	NxSFvNIQD: "framer-v-12a1xt8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"No badge": "JLjMs0za_",
	Desktop: "NxSFvNIQD",
};
var getProps = ({
	badgeImage,
	height,
	id,
	image,
	rightText,
	subtitle,
	title,
	width,
	...props
}) => {
	return {
		...props,
		DeH_yxpqs: rightText ?? props.DeH_yxpqs ?? "Disconnect",
		FYT3Rs6q4: badgeImage ??
			props.FYT3Rs6q4 ?? {
				alt: "",
				pixelHeight: 512,
				pixelWidth: 512,
				src: "https://framerusercontent.com/images/bsRPNP7YUdm2u5tCuMjOv9n3Yk.png?width=512&height=512",
			},
		hftMO6SIO: subtitle ?? props.hftMO6SIO ?? "0x1234...ABCD",
		HPa265xOh: title ?? props.HPa265xOh ?? "Morpho",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "NxSFvNIQD",
		VTgYcB33S: image ??
			props.VTgYcB33S ?? {
				alt: "",
				pixelHeight: 120,
				pixelWidth: 120,
				src: "https://framerusercontent.com/images/IwScelHwHs6NE4F13gF9tXTmrg.svg?width=120&height=120",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		DeH_yxpqs,
		HPa265xOh,
		hftMO6SIO,
		VTgYcB33S,
		FYT3Rs6q4,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NxSFvNIQD",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "JLjMs0za_") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-12a1xt8",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"NxSFvNIQD"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-361e1224-4029-4612-a297-51f349511b71, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-22e7e14f-1f70-49cd-ae98-e88c20549e6b, rgba(255, 255, 255, 0.03))",
							borderBottomLeftRadius: 12,
							borderBottomRightRadius: 12,
							borderTopLeftRadius: 12,
							borderTopRightRadius: 12,
							...style,
						}}
						{...addPropertyOverrides(
							{
								JLjMs0za_: {
									"data-framer-name": "No badge",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(24 + ((componentViewport?.height || 90) - 48 - 24) / 2),
								),
								pixelHeight: 120,
								pixelWidth: 120,
								sizes: "40px",
								...toResponsiveImage(VTgYcB33S),
							}}
							className={"framer-1gznwki"}
							data-border={true}
							data-framer-name={"With ChainIcon"}
							layoutDependency={layoutDependency}
							layoutId={"G1uLwFO1d"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-361e1224-4029-4612-a297-51f349511b71, rgba(255, 255, 255, 0.1))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 99,
								borderBottomRightRadius: 99,
								borderTopLeftRadius: 99,
								borderTopRightRadius: 99,
							}}
						>
							{isDisplayed() && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(24 +
													((componentViewport?.height || 90) - 48 - 24) / 2) +
												24 -
												16,
										),
										pixelHeight: 512,
										pixelWidth: 512,
										sizes: "16px",
										...toResponsiveImage(FYT3Rs6q4),
									}}
									className={"framer-g5v84k"}
									layoutDependency={layoutDependency}
									layoutId={"ye5NCYUmh"}
									style={{
										borderBottomLeftRadius: 99,
										borderBottomRightRadius: 99,
										borderTopLeftRadius: 99,
										borderTopRightRadius: 99,
									}}
								/>
							)}
						</Image>
						<motion.div
							className={"framer-1nf3adp"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"wiNV2V3Xd"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-xvobtk"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"BLhcHmii_"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={HPa265xOh}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-ujo3da"}
										data-styles-preset={"sQrIs9_t0"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))",
										}}
									>
										{"Morpho"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichTextWithTruncateOneLine1hvb3yo
								__fromCanvasComponent={true}
								className={"framer-1hvb3yo"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ZkeT9tcCl"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={hftMO6SIO}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-c9mga6"}
										data-styles-preset={"Xa6VJQy2p"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))",
										}}
									>
										{"0x1234...ABCD"}
									</motion.p>
								</React.Fragment>
							</RichTextWithTruncateOneLine1hvb3yo>
						</motion.div>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1ttjevk-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"i4mDnA7En-container"}
								nodeId={"i4mDnA7En"}
								rendersWithMotion={true}
								scopeId={"V81cUXVhy"}
							>
								<TextGlitch
									color={
										"var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))"
									}
									duration={350}
									font={{
										fontFamily: '"Raveo Variable Variable", sans-serif',
										fontSize: "14px",
										fontStyle: "normal",
										fontWeight: 1e3,
										letterSpacing: "-0.01em",
										lineHeight: "1.2em",
										textAlign: "right",
									}}
									glitch={false}
									height={"100%"}
									id={"i4mDnA7En"}
									layoutId={"i4mDnA7En"}
									scrambleChars={
										"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?"
									}
									scrambleColor={
										"var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))"
									}
									scramblePercent={70}
									speed={50}
									text={DeH_yxpqs}
									variable={{
										optical: 14,
										weight: 550,
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-m1TdF.framer-ujx80h, .framer-m1TdF .framer-ujx80h { display: block; }",
	".framer-m1TdF.framer-12a1xt8 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px 16px 24px 16px; position: relative; width: 358px; }",
	".framer-m1TdF .framer-1gznwki { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 40px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 40px; }",
	".framer-m1TdF .framer-g5v84k { align-content: center; align-items: center; aspect-ratio: 1 / 1; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 16px); justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: absolute; right: 0px; width: 16px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-m1TdF .framer-1nf3adp { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; z-index: 4; }",
	".framer-m1TdF .framer-xvobtk { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-m1TdF .framer-1hvb3yo { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-m1TdF .framer-1ttjevk-container { flex: none; height: auto; position: relative; width: auto; z-index: 1; }",
	...css,
	...css2,
	'.framer-m1TdF[data-border="true"]::after, .framer-m1TdF [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerV81cUXVhy = withCSS(Component, css3, "framer-m1TdF");
var stdin_default = FramerV81cUXVhy;
FramerV81cUXVhy.displayName = "ConnectionCardItem";
FramerV81cUXVhy.defaultProps = {
	height: 90,
	width: 358,
};
addPropertyControls2(FramerV81cUXVhy, {
	variant: {
		options: ["NxSFvNIQD", "JLjMs0za_"],
		optionTitles: ["Desktop", "No badge"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	DeH_yxpqs: {
		defaultValue: "Disconnect",
		title: "rightText",
		type: ControlType2.String,
	},
	HPa265xOh: {
		defaultValue: "Morpho",
		displayTextArea: false,
		title: "title",
		type: ControlType2.String,
	},
	hftMO6SIO: {
		defaultValue: "0x1234...ABCD",
		displayTextArea: false,
		title: "subtitle",
		type: ControlType2.String,
	},
	VTgYcB33S: {
		__defaultAssetReference:
			"data:framer/asset-reference,IwScelHwHs6NE4F13gF9tXTmrg.svg?originalFilename=morpho.svg&width=120&height=120",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,IwScelHwHs6NE4F13gF9tXTmrg.svg?originalFilename=morpho.svg&width=120&height=120",
		},
		title: "image",
		type: ControlType2.ResponsiveImage,
	},
	FYT3Rs6q4: {
		__defaultAssetReference:
			"data:framer/asset-reference,bsRPNP7YUdm2u5tCuMjOv9n3Yk.png?originalFilename=optimism-bridge.png&width=512&height=512",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,bsRPNP7YUdm2u5tCuMjOv9n3Yk.png?originalFilename=optimism-bridge.png&width=512&height=512",
		},
		title: "badgeImage",
		type: ControlType2.ResponsiveImage,
	},
});
var variationAxes3 = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	FramerV81cUXVhy,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Raveo Variable",
					source: "builtIn",
					style: "normal",
					url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
					variationAxes: variationAxes3,
					weight: "1000",
				},
			],
		},
		...TextGlitchFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:connection-card-item
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	Agq1L2jDe: {
		path: "/lib/careers/:slug",
	},
	DEi7PWhxw: {
		path: "/done/coming-soon",
	},
	J_r8CT7G7: {
		path: "/lib/about",
	},
	MiKvYzstd: {
		path: "/done/disconnect",
	},
	Mxb74mbpa: {
		path: "/done/verify-social",
	},
	OegBE_J9e: {
		path: "/lib/home",
	},
	SOf0RbDE_: {
		path: "/lib/blog",
	},
	TQDjkQC2A: {
		path: "/lib/contact",
	},
	UVAM5_4oX: {
		path: "/done/verify",
	},
	XanNBrFME: {
		path: "/kyc",
	},
	YBTUYW5mq: {
		path: "/lib/pricing",
	},
	a5CCfdDiy: {
		path: "/lib/updates/:slug",
	},
	augiA20Il: {
		path: "/",
	},
	cpP7I9WGp: {
		path: "/done/404",
	},
	e9YIc4Uv5: {
		path: "/lib/waitlist",
	},
	inNalAASs: {
		path: "/lib/blog/:slug",
	},
	ixIXvnG3U: {
		path: "/lib/legal/:slug",
	},
	nhNLVf3qq: {
		path: "/connections",
	},
	rX7FOhQc0: {
		path: "/lib/updates",
	},
	so5jTiDIE: {
		path: "/lib/careers",
	},
};

// virtual:connection-card-item
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "JLjMs0za_",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ConnectionCardItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var connection_card_item_default = ComponentWithRoot;
export { connection_card_item_default as default };
