// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c32b11589f2bc68b "humanpass", do not edit manually */
"use client";

// virtual:verify-button
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Success' | 'Error' | 'Dot' // Variant
 * label?: string // Label
 * additional?: string // Additional
 * success?: string // Success
 * error?: string // Error
 * state?: 'Default' | 'Roll' // State
}} Props

 */
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/2VrLbh2ZkaEMiVZdNjIr/Ukar61EQjWNxPc90kL3J/K1WHmn8cr.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	getPropertyControls,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import { LayoutGroup, motion as motion3, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/aeEe477xpzEFqqaZhiTE/ltgP15qtviN0Ho7MrfaG/RollingText.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
import { motion } from "unframer";
var uuidv4 = () => {
	return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
		const r = (Math.random() * 16) | 0;
		const v = c === "x" ? r : (r & 3) | 8;
		return v.toString(16);
	});
};
function RollingText({
	text,
	transition,
	stagger,
	reverse,
	font,
	color,
	textTransform,
	tag,
	padding,
	variable,
	state,
}) {
	const innerClassName = `rolling-text-inner-${uuidv4()}`;
	const Tag = tag;
	const fontSizeStr = font?.fontSize ?? "16px";
	const letterSpacingStr = font?.letterSpacing ?? "0px";
	const rawLineHeight = font?.lineHeight;
	const fontFamily = font?.fontFamily ?? "Inter";
	const fontSizeNum = parseInt(fontSizeStr, 10) || 16;
	let absoluteLineHeightPx;
	if (typeof rawLineHeight === "number") {
		absoluteLineHeightPx = fontSizeNum * rawLineHeight;
	} else if (
		typeof rawLineHeight === "string" &&
		rawLineHeight.includes("em")
	) {
		const emValue = parseFloat(rawLineHeight) || 1.2;
		absoluteLineHeightPx = fontSizeNum * emValue;
	} else if (typeof rawLineHeight === "string") {
		const pxValue = parseFloat(rawLineHeight);
		absoluteLineHeightPx = isNaN(pxValue) ? rawLineHeight : `${pxValue}px`;
	} else {
		absoluteLineHeightPx = fontSizeNum * 1.2;
	}
	const absoluteLineHeightStr =
		typeof absoluteLineHeightPx === "number"
			? `${absoluteLineHeightPx}px`
			: absoluteLineHeightPx;
	const yOffset = `-${absoluteLineHeightStr}`;
	const variableFontStyles = variable
		? {
				fontVariationSettings: `'wght' ${variable.weight}, 'opsz' ${variable.optical}`,
			}
		: {};
	const styles = `
    .${innerClassName} {
      --font-size: ${fontSizeStr};
      --text: ${color};
      --line-height-abs: ${absoluteLineHeightStr};
      box-sizing: border-box; margin: 0; padding: 0; vertical-align: top;
      display: flex; overflow: hidden; width: max-content;
      font-family: ${fontFamily}; font-size: ${fontSizeStr};
      text-transform: ${textTransform}; user-select: none;
      text-shadow: 0 var(--line-height-abs) 0 var(--text);
    }
    .${innerClassName} span {
      display: block; -webkit-backface-visibility: hidden; backface-visibility: hidden;
      white-space: pre; flex-shrink: 0;
      font-family: inherit; font-weight: inherit; font-style: inherit;
      font-size: inherit; letter-spacing: inherit;
      line-height: ${rawLineHeight ?? 1.2};
      color: var(--text);
    }
  `;
	const wrapperStyle = {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		width: "100%",
		height: "100%",
		overflow: "hidden",
		padding,
		boxSizing: "border-box",
	};
	const spanVariants = {
		initial: {
			y: "0%",
		},
		roll: {
			y: yOffset,
		},
	};
	const baseDuration =
		typeof transition?.duration === "number" ? transition.duration : 0.5;
	const staggerFactor = stagger / 100;
	const animateState = state === "Roll" ? "roll" : "initial";
	return (
		<div style={wrapperStyle}>
			<Tag className={innerClassName} style={variableFontStyles}>
				{[...text].map((str, index) => {
					const charIndex = reverse ? text.length - 1 - index : index;
					const delay =
						text.length > 0
							? (baseDuration / text.length) * charIndex * staggerFactor
							: 0;
					const motionSpanStyle = {
						display: "block",
						...font,
						...variableFontStyles,
					};
					return (
						<motion.span
							variants={spanVariants}
							initial={"initial"}
							animate={animateState}
							transition={{
								...transition,
								delay,
							}}
							style={motionSpanStyle}
						>
							{str === " " ? "\xA0" : str}
						</motion.span>
					);
				})}
			</Tag>
			<style>{styles}</style>
		</div>
	);
}
RollingText.displayName = "Rolling Text";
var defaultFont = {
	fontFamily: "Inter",
	fontWeight: "400",
	fontSize: "16px",
	fontStyle: "normal",
	letterSpacing: "0px",
	lineHeight: 1.2,
};
var defaultTransition = {
	type: "spring",
	duration: 0.4,
	bounce: 0,
};
addPropertyControls(RollingText, {
	text: {
		type: ControlType.String,
		title: "Text",
		defaultValue: "Rolling Text",
	},
	font: {
		type: ControlType.Font,
		title: "Font",
		controls: "extended",
		defaultValue: defaultFont,
	},
	variable: {
		type: ControlType.Object,
		title: "Variable",
		controls: {
			optical: {
				type: ControlType.Number,
				title: "Optical",
				min: 14,
				max: 32,
				step: 1,
				defaultValue: 16,
			},
			weight: {
				type: ControlType.Number,
				title: "Weight",
				min: 100,
				max: 900,
				step: 1,
				defaultValue: 400,
			},
		},
		defaultValue: {
			optical: 16,
			weight: 400,
		},
	},
	color: {
		type: ControlType.Color,
		title: "Color",
		defaultValue: "#808080",
	},
	transition: {
		type: ControlType.Transition,
		title: "Transition",
		defaultValue: defaultTransition,
	},
	stagger: {
		title: "Stagger",
		type: ControlType.Number,
		min: 0,
		max: 100,
		step: 1,
		defaultValue: 35,
		unit: "%",
	},
	padding: {
		title: "Padding",
		type: ControlType.Padding,
		defaultValue: "0px",
	},
	reverse: {
		type: ControlType.Boolean,
		title: "Reverse",
		defaultValue: false,
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	textTransform: {
		title: "Transform",
		type: ControlType.Enum,
		defaultValue: "none",
		options: ["none", "uppercase", "lowercase", "capitalize"],
		optionTitles: ["None", "Uppercase", "Lowercase", "Capitalize"],
	},
	tag: {
		type: ControlType.Enum,
		title: "Tag",
		options: ["p", "span", "h1", "h2", "h3", "h4", "h5", "h6"],
		optionTitles: ["p", "span", "h1", "h2", "h3", "h4", "h5", "h6"],
		defaultValue: "p",
	},
	state: {
		type: ControlType.Enum,
		title: "State",
		options: ["Default", "Roll"],
		optionTitles: ["Default", "Roll"],
		displaySegmentedControl: true,
		segmentedControlDirection: "vertical",
		defaultValue: "Default",
	},
});

// /:https://framerusercontent.com/modules/9NKBHiJNZccgziYcoXdO/9FpomhappY44CQdswwtx/nmO3BT1ni.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"BI;Raveo Variable/variable/v0",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
]);
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Raveo Variable",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
				variationAxes,
				weight: "1000",
			},
		],
	},
];
var css = [
	'.framer-ZogxA .framer-styles-preset-yplpmu:not(.rich-text-wrapper), .framer-ZogxA .framer-styles-preset-yplpmu.rich-text-wrapper p { --framer-font-family: "Raveo Variable Variable", sans-serif; --framer-font-family-bold: "Raveo Variable Variable", sans-serif; --framer-font-family-bold-italic: "Raveo Variable Variable", sans-serif; --framer-font-family-italic: "Raveo Variable Variable", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: normal; --framer-font-style-italic: normal; --framer-font-variation-axes: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold-italic: "opsz" 14, "wght" 550; --framer-font-variation-axes-italic: "opsz" 14, "wght" 550; --framer-font-weight: 1000; --framer-font-weight-bold: 1000; --framer-font-weight-bold-italic: 1000; --framer-font-weight-italic: 1000; --framer-letter-spacing: -0.01em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className = "framer-ZogxA";

// /:https://framerusercontent.com/modules/98ORxWqlwYbJSprEgxIC/flBGuhQnA9EJbbUQJTgQ/sQrIs9_t0.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"BI;Raveo Variable/variable/v0",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
]);
var variationAxes2 = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Raveo Variable",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
				variationAxes: variationAxes2,
				weight: "1000",
			},
		],
	},
];
var css2 = [
	'.framer-D0GFO .framer-styles-preset-ujo3da:not(.rich-text-wrapper), .framer-D0GFO .framer-styles-preset-ujo3da.rich-text-wrapper p { --framer-font-family: "Raveo Variable Variable", sans-serif; --framer-font-family-bold: "Raveo Variable Variable", sans-serif; --framer-font-family-bold-italic: "Raveo Variable Variable", sans-serif; --framer-font-family-italic: "Raveo Variable Variable", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: normal; --framer-font-style-italic: normal; --framer-font-variation-axes: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold-italic: "opsz" 14, "wght" 550; --framer-font-variation-axes-italic: "opsz" 14, "wght" 550; --framer-font-weight: 1000; --framer-font-weight-bold: 1000; --framer-font-weight-bold-italic: 1000; --framer-font-weight-italic: 1000; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className2 = "framer-D0GFO";

// /:https://framerusercontent.com/modules/pO7ywx3M4YnpNdsCU95X/vX6L2ZbUqgFkz71Lz2gZ/GEucEkwam.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	motion as motion2,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = `url('data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><g opacity="0.3"><path d="M 7 0 C 10.866 0 14 3.134 14 7 C 14 10.866 10.866 14 7 14 C 3.134 14 0 10.866 0 7 C 0 3.134 3.134 0 7 0 Z" fill="transparent" height="14px" id="FhSXGkt6l" stroke-dasharray="0" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" stroke-width="2" stroke="var(--13bnw74, rgb(255, 255, 255))" transform="translate(5 5)" width="14px"/></g><path d="M 7 0 C 10.866 0 14 3.134 14 7 C 14 10.866 10.866 14 7 14 C 3.134 14 0 10.866 0 7 C 0 3.134 3.134 0 7 0 Z" fill="transparent" height="14px" id="Wsdwr4c7J" stroke-dasharray="7" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" stroke-width="2" stroke="var(--13bnw74, rgb(255, 255, 255))" transform="translate(5 5)" width="14px"/></svg>') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)`;
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion2.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps = ({ color, fill, height, id, width, ...props }) => {
	return {
		...props,
		HN7TZix3o: color ?? props.HN7TZix3o ?? "rgb(255, 255, 255)",
		judN_LhGq: fill ?? props.judN_LhGq ?? "rgb(255, 255, 255)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		HN7TZix3o,
		judN_LhGq,
		...restProps
	} = getProps(props);
	return (
		<SVG
			{...restProps}
			className={cx("framer-6m7FC", className3)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--13bnw74": HN7TZix3o,
				...style,
			}}
		/>
	);
});
var css3 = [
	`.framer-6m7FC { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--13bnw74); mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css3, "framer-6m7FC");
Icon.displayName = "Loader";
var stdin_default = Icon;
addPropertyControls2(Icon, {
	HN7TZix3o: {
		defaultValue: "rgb(255, 255, 255)",
		hidden: false,
		title: "Color",
		type: ControlType2.Color,
	},
	judN_LhGq: {
		defaultValue: "rgb(255, 255, 255)",
		hidden: true,
		title: "Fill",
		type: ControlType2.Color,
	},
});

// /:https://framerusercontent.com/modules/2VrLbh2ZkaEMiVZdNjIr/Ukar61EQjWNxPc90kL3J/K1WHmn8cr.js
var LoaderFonts = getFonts(stdin_default);
var LoaderWithFX = withFX(stdin_default);
var RollingTextFonts = getFonts(RollingText);
var RollingTextControls = getPropertyControls(RollingText);
var enabledGestures = {
	gYgSKsBU8: {
		hover: true,
	},
};
var cycleOrder = [
	"gYgSKsBU8",
	"rXRdCdhCR",
	"oW3sD9pGc",
	"phCJnqGoT",
	"JmlxKWZWH",
];
var serializationHash = "framer-c2GCV";
var variantClassNames = {
	gYgSKsBU8: "framer-v-cvnr0t",
	JmlxKWZWH: "framer-v-1w3nwqq",
	oW3sD9pGc: "framer-v-129f9xc",
	phCJnqGoT: "framer-v-stk2pg",
	rXRdCdhCR: "framer-v-21x1f5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 0.5,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var transformTemplate2 = (_, t) => `translateY(-50%) ${t}`;
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion3.create(React2.Fragment);
var humanReadableEnumMap = {
	Default: "Default",
	Roll: "Roll",
};
var humanReadableVariantMap = {
	Default: "gYgSKsBU8",
	Dot: "JmlxKWZWH",
	Error: "phCJnqGoT",
	Loading: "rXRdCdhCR",
	Success: "oW3sD9pGc",
};
var getProps2 = ({
	additional,
	error,
	height,
	id,
	label,
	state,
	success,
	width,
	...props
}) => {
	return {
		...props,
		puP6A2dz_: additional ?? props.puP6A2dz_,
		qCxNvGxTB:
			humanReadableEnumMap[state] ?? state ?? props.qCxNvGxTB ?? "Roll",
		SB93GG782: success ?? props.SB93GG782 ?? "Verification complete!",
		SMZpJms0Q: label ?? props.SMZpJms0Q ?? "Verify for",
		v5N8mGmrX: error ?? props.v5N8mGmrX ?? "Something went wrong",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "gYgSKsBU8",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		SMZpJms0Q,
		puP6A2dz_,
		SB93GG782,
		v5N8mGmrX,
		qCxNvGxTB,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "gYgSKsBU8",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "rXRdCdhCR") return true;
		return false;
	};
	const visible = isSet(puP6A2dz_);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion3.button
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-cvnr0t",
							className3,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						draggable={"false"}
						layoutDependency={layoutDependency}
						layoutId={"gYgSKsBU8"}
						ref={refBinding}
						style={{
							backdropFilter: "blur(2px)",
							backgroundColor:
								"var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							filter: "none",
							WebkitBackdropFilter: "blur(2px)",
							WebkitFilter: "none",
							...style,
						}}
						variants={{
							"gYgSKsBU8-hover": {
								filter: "brightness(0.8)",
								WebkitFilter: "brightness(0.8)",
							},
							oW3sD9pGc: {
								backgroundColor: "rgba(255, 255, 255, 0)",
							},
							phCJnqGoT: {
								backgroundColor: "rgba(219, 44, 44, 0.15)",
							},
						}}
						{...addPropertyOverrides(
							{
								"gYgSKsBU8-hover": {
									"data-framer-name": void 0,
								},
								JmlxKWZWH: {
									"data-framer-name": "Dot",
								},
								oW3sD9pGc: {
									"data-framer-name": "Success",
								},
								phCJnqGoT: {
									"data-framer-name": "Error",
								},
								rXRdCdhCR: {
									"data-framer-name": "Loading",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<LoaderWithFX
								__framer__loop={animation}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"loop"}
								__framer__loopTransition={transition2}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={0}
								animated={true}
								className={"framer-dvz2zt"}
								layoutDependency={layoutDependency}
								layoutId={"se1QhVG4t"}
								style={{
									"--13bnw74":
										"var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))",
									opacity: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									rXRdCdhCR: {
										opacity: 1,
									},
								}}
								{...addPropertyOverrides(
									{
										rXRdCdhCR: {
											__targetOpacity: 1,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						<motion3.div
							className={"framer-ak4oqj"}
							data-framer-name={"Success"}
							layoutDependency={layoutDependency}
							layoutId={"lXA1l3e8E"}
							style={{
								filter: "blur(2px)",
								opacity: 0,
								scale: 0.9,
								WebkitFilter: "blur(2px)",
							}}
							transformTemplate={transformTemplate1}
							variants={{
								oW3sD9pGc: {
									filter: "blur(0px)",
									opacity: 1,
									scale: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
							{...addPropertyOverrides(
								{
									oW3sD9pGc: {
										transformTemplate: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-hffr8n"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ojo14e8uA"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={SB93GG782}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										oW3sD9pGc: {
											children: (
												<React2.Fragment>
													<motion3.p
														className={"framer-styles-preset-yplpmu"}
														data-styles-preset={"nmO3BT1ni"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)))",
														}}
													>
														{"Verification complete!"}
													</motion3.p>
												</React2.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion3.p
										className={"framer-styles-preset-ujo3da"}
										data-styles-preset={"sQrIs9_t0"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)))",
										}}
									>
										{"Thanks for your application!"}
									</motion3.p>
								</React2.Fragment>
							</RichText>
						</motion3.div>
						<motion3.div
							className={"framer-1qld652"}
							data-framer-name={"Error"}
							layoutDependency={layoutDependency}
							layoutId={"OhG2hLvNb"}
							style={{
								filter: "blur(2px)",
								opacity: 0,
								scale: 0.9,
								WebkitFilter: "blur(2px)",
							}}
							transformTemplate={transformTemplate1}
							variants={{
								phCJnqGoT: {
									filter: "blur(0px)",
									opacity: 1,
									scale: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
							{...addPropertyOverrides(
								{
									phCJnqGoT: {
										transformTemplate: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1ppdry9"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"rL34T7JjF"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-1e8433a6-dbc9-469b-bb1a-972dd419d298, rgb(219, 44, 44))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={v5N8mGmrX}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion3.p
										className={"framer-styles-preset-yplpmu"}
										data-styles-preset={"nmO3BT1ni"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-1e8433a6-dbc9-469b-bb1a-972dd419d298, rgb(219, 44, 44)))",
										}}
									>
										{"Something went wrong"}
									</motion3.p>
								</React2.Fragment>
							</RichText>
						</motion3.div>
						<motion3.div
							className={"framer-12max6b"}
							data-framer-name={"Label"}
							layoutDependency={layoutDependency}
							layoutId={"floUiZWp3"}
							style={{
								filter: "none",
								opacity: 1,
								scale: 1,
								WebkitFilter: "none",
							}}
							variants={{
								"gYgSKsBU8-hover": {
									filter: "none",
									opacity: 1,
									scale: 1,
									WebkitFilter: "none",
								},
								JmlxKWZWH: {
									filter: "blur(2px)",
									opacity: 0,
									scale: 1.1,
									WebkitFilter: "blur(2px)",
								},
								oW3sD9pGc: {
									filter: "blur(2px)",
									opacity: 0,
									scale: 1.1,
									WebkitFilter: "blur(2px)",
								},
								phCJnqGoT: {
									filter: "blur(2px)",
									opacity: 0,
									scale: 1.1,
									WebkitFilter: "blur(2px)",
								},
								rXRdCdhCR: {
									filter: "blur(2px)",
									opacity: 0,
									scale: 1.1,
									WebkitFilter: "blur(2px)",
								},
							}}
							{...addPropertyOverrides(
								{
									oW3sD9pGc: {
										transformTemplate: transformTemplate2,
									},
									phCJnqGoT: {
										transformTemplate: transformTemplate1,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{visible && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ol9h13"}
									data-framer-name={"Additional"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"zIpq734k4"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={puP6A2dz_}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion3.p
											className={"framer-styles-preset-ujo3da"}
											data-styles-preset={"sQrIs9_t0"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0)))",
											}}
										>
											{"Apply for"}
										</motion3.p>
									</React2.Fragment>
								</RichText>
							)}
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1rsk3c9-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"hRG37wYUN-container"}
									nodeId={"hRG37wYUN"}
									rendersWithMotion={true}
									scopeId={"K1WHmn8cr"}
								>
									<RollingText
										color={
											"var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))"
										}
										font={{
											fontFamily: '"Raveo Variable Variable", sans-serif',
											fontSize: "16px",
											fontStyle: "normal",
											fontWeight: 1e3,
											letterSpacing: "0em",
											lineHeight: "1.2em",
										}}
										height={"100%"}
										id={"hRG37wYUN"}
										layoutId={"hRG37wYUN"}
										padding={"0px"}
										reverse={false}
										stagger={35}
										state={qCxNvGxTB}
										style={{
											height: "100%",
										}}
										tag={"p"}
										text={SMZpJms0Q}
										textTransform={"none"}
										transition={{
											bounce: 0,
											delay: 0,
											duration: 0.4,
											type: "spring",
										}}
										variable={{
											optical: 16,
											weight: 550,
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion3.div>
						<motion3.div
							className={"framer-h4nn71"}
							data-framer-name={"BG"}
							layoutDependency={layoutDependency}
							layoutId={"lomFTzKfT"}
							style={{
								backgroundColor:
									"var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								opacity: 0,
							}}
							variants={{
								oW3sD9pGc: {
									opacity: 0.1,
								},
							}}
						/>
					</motion3.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-c2GCV.framer-1cvlmi1, .framer-c2GCV .framer-1cvlmi1 { display: block; }",
	".framer-c2GCV.framer-cvnr0t { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 52px; justify-content: center; overflow: hidden; padding: 0px 18px 0px 18px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-c2GCV .framer-dvz2zt { flex: none; height: var(--framer-aspect-ratio-supported, 24px); left: 50%; position: absolute; top: 50%; width: 24px; z-index: 5; }",
	".framer-c2GCV .framer-ak4oqj, .framer-c2GCV .framer-1qld652 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 50%; width: min-content; z-index: 1; }",
	".framer-c2GCV .framer-hffr8n, .framer-c2GCV .framer-1ppdry9, .framer-c2GCV .framer-ol9h13 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-c2GCV .framer-12max6b { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 3.5px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-c2GCV .framer-1rsk3c9-container { flex: none; height: 50px; position: relative; width: auto; }",
	".framer-c2GCV .framer-h4nn71 { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 0; }",
	".framer-c2GCV.framer-v-129f9xc.framer-cvnr0t, .framer-c2GCV.framer-v-stk2pg.framer-cvnr0t { cursor: default; }",
	".framer-c2GCV.framer-v-129f9xc .framer-ak4oqj, .framer-c2GCV.framer-v-stk2pg .framer-1qld652 { left: unset; position: relative; top: unset; }",
	".framer-c2GCV.framer-v-129f9xc .framer-12max6b { left: 55px; position: absolute; top: 50%; }",
	".framer-c2GCV.framer-v-stk2pg .framer-12max6b { left: 50%; position: absolute; top: 50%; z-index: 1; }",
	".framer-c2GCV.framer-v-1w3nwqq.framer-cvnr0t { height: 40px; width: 40px; }",
	".framer-c2GCV.framer-v-cvnr0t.hover .framer-1rsk3c9-container { cursor: pointer; }",
	...css2,
	...css,
];
var FramerK1WHmn8cr = withCSS2(Component2, css4, "framer-c2GCV");
var stdin_default2 = FramerK1WHmn8cr;
FramerK1WHmn8cr.displayName = "Verify Button";
FramerK1WHmn8cr.defaultProps = {
	height: 52,
	width: 108.5,
};
addPropertyControls3(FramerK1WHmn8cr, {
	variant: {
		options: ["gYgSKsBU8", "rXRdCdhCR", "oW3sD9pGc", "phCJnqGoT", "JmlxKWZWH"],
		optionTitles: ["Default", "Loading", "Success", "Error", "Dot"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	SMZpJms0Q: {
		defaultValue: "Verify for",
		displayTextArea: false,
		title: "Label",
		type: ControlType3.String,
	},
	puP6A2dz_: {
		defaultValue: "",
		title: "Additional",
		type: ControlType3.String,
	},
	SB93GG782: {
		defaultValue: "Verification complete!",
		placeholder: "",
		title: "Success",
		type: ControlType3.String,
	},
	v5N8mGmrX: {
		defaultValue: "Something went wrong",
		description: "",
		title: "Error",
		type: ControlType3.String,
	},
	qCxNvGxTB: RollingTextControls?.["state"] && {
		...RollingTextControls["state"],
		defaultValue: "Roll",
		description:
			"Used for triggering rolling of text when used within another component.",
		hidden: void 0,
		title: "State",
	},
});
var variationAxes3 = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	FramerK1WHmn8cr,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Raveo Variable",
					source: "builtIn",
					style: "normal",
					url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
					variationAxes: variationAxes3,
					weight: "1000",
				},
			],
		},
		...LoaderFonts,
		...RollingTextFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:verify-button
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	Agq1L2jDe: {
		path: "/lib/careers/:slug",
	},
	DEi7PWhxw: {
		path: "/done/coming-soon",
	},
	J_r8CT7G7: {
		path: "/lib/about",
	},
	MiKvYzstd: {
		path: "/disconnect",
	},
	Mxb74mbpa: {
		path: "/verify-social",
	},
	OegBE_J9e: {
		path: "/lib/home",
	},
	SOf0RbDE_: {
		path: "/lib/blog",
	},
	TQDjkQC2A: {
		path: "/lib/contact",
	},
	UVAM5_4oX: {
		path: "/verify",
	},
	XanNBrFME: {
		path: "/kyc",
	},
	YBTUYW5mq: {
		path: "/lib/pricing",
	},
	a5CCfdDiy: {
		path: "/lib/updates/:slug",
	},
	augiA20Il: {
		path: "/",
	},
	cpP7I9WGp: {
		path: "/done/404",
	},
	e9YIc4Uv5: {
		path: "/lib/waitlist",
	},
	inNalAASs: {
		path: "/lib/blog/:slug",
	},
	ixIXvnG3U: {
		path: "/lib/legal/:slug",
	},
	nhNLVf3qq: {
		path: "/connections",
	},
	rX7FOhQc0: {
		path: "/lib/updates",
	},
	so5jTiDIE: {
		path: "/lib/careers",
	},
};

// virtual:verify-button
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "oW3sD9pGc",
	xl: "gYgSKsBU8",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VerifyButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var verify_button_default = ComponentWithRoot;
export { verify_button_default as default };
