// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c32b11589f2bc68b "humanpass", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'real' // Variant
 * price1?: string // price1
 * price2?: string // price2
 * chainCount?: string // chainCount
 * diff?: string // diff
}} Props

 */
import {
	className,
	css,
	fonts,
	withTruncateOneLine,
} from "./chunks/chunk-C7B642EE.js";
import { stdin_default } from "./chunks/chunk-U6SQYF76.js";
import "./chunks/chunk-R527CHIA.js";
import { routes } from "./chunks/chunk-QMBC2E5Z.js";
import "./chunks/chunk-WSFCRVEQ.js";

// virtual:portfolio-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/KWixij1MJt5C2G9UHSkv/djzk676mFDMzowlwfKDj/rtwiOOpcU.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCodeBoundaryForOverrides,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/yXFrli89e4rnKW93WjH0/Q7zcw2TI3MAi3ZiJezEE/bRzBDjLMv.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"BI;Raveo Variable/variable/v0",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNDUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNDUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNDUw",
]);
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Raveo Variable",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
				variationAxes,
				weight: "1000",
			},
		],
	},
];
var css2 = [
	'.framer-ZUskE .framer-styles-preset-d4fts2:not(.rich-text-wrapper), .framer-ZUskE .framer-styles-preset-d4fts2.rich-text-wrapper p { --framer-font-family: "Raveo Variable Variable", sans-serif; --framer-font-family-bold: "Raveo Variable Variable", sans-serif; --framer-font-family-bold-italic: "Raveo Variable Variable", sans-serif; --framer-font-family-italic: "Raveo Variable Variable", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: normal; --framer-font-style-italic: normal; --framer-font-variation-axes: "opsz" 14, "wght" 450; --framer-font-variation-axes-bold: "opsz" 14, "wght" 450; --framer-font-variation-axes-bold-italic: "opsz" 14, "wght" 450; --framer-font-variation-axes-italic: "opsz" 14, "wght" 450; --framer-font-weight: 1000; --framer-font-weight-bold: 1000; --framer-font-weight-bold-italic: 1000; --framer-font-weight-italic: 1000; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 24px; --framer-text-alignment: left; --framer-text-color: var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className2 = "framer-ZUskE";

// /:https://framerusercontent.com/modules/nvE0yCGD6meyDk8Z0Uhl/YGGhmvTuvCAynIU5BfzG/cgp7nxgQP.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"BI;Raveo Variable/variable/v0",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
	"BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
]);
var variationAxes2 = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Raveo Variable",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
				variationAxes: variationAxes2,
				weight: "1000",
			},
		],
	},
];
var css3 = [
	`.framer-glsuf .framer-styles-preset-90li6l:not(.rich-text-wrapper), .framer-glsuf .framer-styles-preset-90li6l.rich-text-wrapper h1 { --framer-font-family: "Raveo Variable Variable", sans-serif; --framer-font-family-bold: "Raveo Variable Variable", sans-serif; --framer-font-family-bold-italic: "Raveo Variable Variable", sans-serif; --framer-font-family-italic: "Raveo Variable Variable", sans-serif; --framer-font-open-type-features: 'tnum' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 2.2); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: normal; --framer-font-style-italic: normal; --framer-font-variation-axes: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold-italic: "opsz" 14, "wght" 550; --framer-font-variation-axes-italic: "opsz" 14, "wght" 550; --framer-font-weight: 1000; --framer-font-weight-bold: 1000; --framer-font-weight-bold-italic: 1000; --framer-font-weight-italic: 1000; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className3 = "framer-glsuf";

// /:https://framerusercontent.com/modules/KWixij1MJt5C2G9UHSkv/djzk676mFDMzowlwfKDj/rtwiOOpcU.js
var RichTextWithTruncateOneLineph3myg = withCodeBoundaryForOverrides(RichText, {
	nodeId: "mrgTzA2UX",
	override: withTruncateOneLine,
	scopeId: "rtwiOOpcU",
});
var RichTextWithTruncateOneLineixo20j = withCodeBoundaryForOverrides(RichText, {
	nodeId: "TkpDVi92u",
	override: withTruncateOneLine,
	scopeId: "rtwiOOpcU",
});
var RichTextWithTruncateOneLinexrq50f = withCodeBoundaryForOverrides(RichText, {
	nodeId: "l_6P11u5k",
	override: withTruncateOneLine,
	scopeId: "rtwiOOpcU",
});
var MainSiteGridBorderFonts = getFonts(stdin_default);
var cycleOrder = ["bwNMSxDqZ", "urpnMzLEm"];
var serializationHash = "framer-W83lO";
var variantClassNames = {
	bwNMSxDqZ: "framer-v-1jbitbc",
	urpnMzLEm: "framer-v-1rx33dq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "bwNMSxDqZ",
	real: "urpnMzLEm",
};
var getProps = ({
	chainCount,
	diff,
	height,
	id,
	price1,
	price2,
	width,
	...props
}) => {
	return {
		...props,
		AtmCn84I2: price2 ?? props.AtmCn84I2 ?? ".52",
		lu3wTvpkh: price1 ?? props.lu3wTvpkh ?? "$109",
		PHiMAXwcv: chainCount ?? props.PHiMAXwcv ?? "+3 chains",
		rpAaLLi6l: diff ?? props.rpAaLLi6l ?? "+0.33% ($0.36) Today",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "bwNMSxDqZ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		lu3wTvpkh,
		AtmCn84I2,
		PHiMAXwcv,
		rpAaLLi6l,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "bwNMSxDqZ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "urpnMzLEm") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1jbitbc",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"bwNMSxDqZ"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-361e1224-4029-4612-a297-51f349511b71, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							borderBottomLeftRadius: 12,
							borderBottomRightRadius: 12,
							borderTopLeftRadius: 12,
							borderTopRightRadius: 12,
							...style,
						}}
						{...addPropertyOverrides(
							{
								urpnMzLEm: {
									"data-framer-name": "real",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-xasvgc"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"yi3HN1lWI"}
						>
							<motion.div
								className={"framer-1qbzl4z"}
								layoutDependency={layoutDependency}
								layoutId={"I_Y0RgGWn"}
							>
								<RichTextWithTruncateOneLineph3myg
									__fromCanvasComponent={true}
									className={"framer-ph3myg"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"mrgTzA2UX"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-d4fts2"}
											data-styles-preset={"bRzBDjLMv"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))",
											}}
										>
											{"Portfolio"}
										</motion.p>
									</React.Fragment>
								</RichTextWithTruncateOneLineph3myg>
								{isDisplayed() && (
									<motion.div
										className={"framer-cbce4z"}
										layoutDependency={layoutDependency}
										layoutId={"D57Lnt4Zb"}
									>
										<motion.div
											className={"framer-clyb9h"}
											layoutDependency={layoutDependency}
											layoutId={"RvQ4NoWDI"}
											style={{
												backgroundColor:
													"var(--token-361e1224-4029-4612-a297-51f349511b71, rgba(255, 255, 255, 0.1))",
												borderBottomLeftRadius: 99,
												borderBottomRightRadius: 99,
												borderTopLeftRadius: 99,
												borderTopRightRadius: 99,
											}}
										>
											<SVG
												className={"framer-mnsxf4"}
												layoutDependency={layoutDependency}
												layoutId={"Va_kDaw8j"}
												opacity={1}
												requiresOverflowVisible={false}
												svg={
													'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 9.147 13.913" overflow="visible"><g><path d="M 4.574 0 L 4.574 5.141 L 9.147 7.086 Z" fill="rgb(143,252,243)"></path><path d="M 4.574 0 L 0 7.085 L 4.574 5.142 Z" fill="rgb(202,188,248)"></path><path d="M 4.574 10.418 L 4.574 13.913 L 9.147 7.896 Z" fill="rgb(203,167,245)"></path><path d="M 4.574 13.913 L 4.574 10.418 L 0 7.896 Z" fill="rgb(116,160,243)"></path><path d="M 4.574 9.608 L 9.147 7.086 L 4.574 5.141 Z" fill="rgb(203,167,245)"></path><path d="M 0 7.086 L 4.574 9.608 L 4.574 5.141 Z" fill="rgb(116,160,243)"></path><path d="M 4.574 9.608 L 0 7.086 L 4.574 0 L 9.147 7.085 Z M 4.5 5.107 L 4.5 0.38 L 0.303 6.881 Z M 4.5 9.406 L 4.5 5.259 L 0.241 7.058 Z M 4.646 5.259 L 4.646 9.406 L 8.902 7.058 Z M 4.646 5.107 L 8.843 6.881 L 4.646 0.38 Z" fill="rgb(32,38,153)"></path><path d="M 9.147 4.861 L 4.574 10.882 L 0 4.862 L 4.574 7.332 Z M 4.5 10.549 L 4.5 7.453 L 0.512 5.296 Z M 4.646 7.453 L 4.646 10.549 L 8.635 5.296 Z" fill="rgb(32,38,153)"></path></g></svg>'
												}
												withExternalLayout={true}
											>
												<SVG
													className={"framer-15qrl3x"}
													layoutDependency={layoutDependency}
													layoutId={"l9pVH5jCX"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.574 7.086" overflow="visible"><path d="M 0 0 L 0 5.141 L 4.574 7.086 Z" fill="rgb(143,252,243)"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-cibkwa"}
													layoutDependency={layoutDependency}
													layoutId={"ZhWfOEHdS"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.574 7.085" overflow="visible"><path d="M 4.574 0 L 0 7.085 L 4.574 5.142 Z" fill="rgb(202,188,248)"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-1lq1r84"}
													layoutDependency={layoutDependency}
													layoutId={"bZEtbwNBy"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.574 6.017" overflow="visible"><path d="M 0 2.522 L 0 6.017 L 4.574 0 Z" fill="rgb(203,167,245)"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-4bv7jq"}
													layoutDependency={layoutDependency}
													layoutId={"sIBo067i7"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.574 6.017" overflow="visible"><path d="M 4.574 6.017 L 4.574 2.522 L 0 0 Z" fill="rgb(116,160,243)"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-w7d0za"}
													layoutDependency={layoutDependency}
													layoutId={"ascw3PtJb"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.574 4.466" overflow="visible"><path d="M 0 4.466 L 4.574 1.945 L 0 0 Z" fill="rgb(203,167,245)"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-a8n6rb"}
													layoutDependency={layoutDependency}
													layoutId={"akmzqWBfB"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.574 4.466" overflow="visible"><path d="M 0 1.945 L 4.574 4.466 L 4.574 0 Z" fill="rgb(116,160,243)"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-kkdaxr"}
													layoutDependency={layoutDependency}
													layoutId={"LG8yCztWY"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 9.147 9.608" overflow="visible"><path d="M 4.574 9.608 L 0 7.086 L 4.574 0 L 9.147 7.085 Z M 4.5 5.107 L 4.5 0.38 L 0.303 6.881 Z M 4.5 9.406 L 4.5 5.259 L 0.241 7.058 Z M 4.646 5.259 L 4.646 9.406 L 8.902 7.058 Z M 4.646 5.107 L 8.843 6.881 L 4.646 0.38 Z" fill="rgb(32,38,153)"></path></svg>'
													}
													withExternalLayout={true}
												>
													<SVG
														className={"framer-1e4472v"}
														layoutDependency={layoutDependency}
														layoutId={"JhjG1iyw9"}
														opacity={1}
														requiresOverflowVisible={false}
														svg={
															'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 9.147 9.608" overflow="visible"><path d="M 4.574 9.608 L 0 7.086 L 4.574 0 L 9.147 7.085 Z" fill="transparent"></path></svg>'
														}
														withExternalLayout={true}
													/>
													<SVG
														className={"framer-1avndow"}
														layoutDependency={layoutDependency}
														layoutId={"BTMDyCJU9"}
														opacity={1}
														requiresOverflowVisible={false}
														svg={
															'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.197 6.501" overflow="visible"><path d="M 0 6.501 L 4.197 0 L 4.197 4.727 Z" fill="transparent"></path></svg>'
														}
														withExternalLayout={true}
													/>
													<SVG
														className={"framer-14mtm2k"}
														layoutDependency={layoutDependency}
														layoutId={"AAv8NSFxB"}
														opacity={1}
														requiresOverflowVisible={false}
														svg={
															'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.259 4.146" overflow="visible"><path d="M 0 1.798 L 4.259 0 L 4.259 4.146 Z" fill="transparent"></path></svg>'
														}
														withExternalLayout={true}
													/>
													<SVG
														className={"framer-l8xq3l"}
														layoutDependency={layoutDependency}
														layoutId={"PvfWyVJe5"}
														opacity={1}
														requiresOverflowVisible={false}
														svg={
															'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.256 4.146" overflow="visible"><path d="M 0 0 L 0 4.146 L 4.256 1.798 Z" fill="transparent"></path></svg>'
														}
														withExternalLayout={true}
													/>
													<SVG
														className={"framer-1nnc3nk"}
														layoutDependency={layoutDependency}
														layoutId={"JSdkiVJMO"}
														opacity={1}
														requiresOverflowVisible={false}
														svg={
															'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.197 6.501" overflow="visible"><path d="M 0 4.727 L 4.197 6.501 L 0 0 Z" fill="transparent"></path></svg>'
														}
														withExternalLayout={true}
													/>
												</SVG>
												<SVG
													className={"framer-vtha3w"}
													layoutDependency={layoutDependency}
													layoutId={"e7uTubhDL"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 9.147 6.02" overflow="visible"><path d="M 9.147 0 L 4.574 6.02 L 0 0.001 L 4.574 2.47 Z M 4.5 5.688 L 4.5 2.592 L 0.512 0.435 Z M 4.646 2.592 L 4.646 5.688 L 8.635 0.435 Z" fill="rgb(32,38,153)"></path></svg>'
													}
													withExternalLayout={true}
												>
													<SVG
														className={"framer-1gpw75u"}
														layoutDependency={layoutDependency}
														layoutId={"eyhq8LZrO"}
														opacity={1}
														requiresOverflowVisible={false}
														svg={
															'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 9.147 6.02" overflow="visible"><path d="M 4.574 2.47 L 0 0.001 L 4.574 6.02 L 9.147 0 Z" fill="transparent"></path></svg>'
														}
														withExternalLayout={true}
													/>
													<SVG
														className={"framer-of7sfx"}
														layoutDependency={layoutDependency}
														layoutId={"Pe7s5ftio"}
														opacity={1}
														requiresOverflowVisible={false}
														svg={
															'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 3.988 5.253" overflow="visible"><path d="M 0 0 L 3.988 2.157 L 3.988 5.253 Z" fill="transparent"></path></svg>'
														}
														withExternalLayout={true}
													/>
													<SVG
														className={"framer-1bwy0aj"}
														layoutDependency={layoutDependency}
														layoutId={"XAJ2oFaDR"}
														opacity={1}
														requiresOverflowVisible={false}
														svg={
															'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 3.989 5.253" overflow="visible"><path d="M 0 2.157 L 0 5.253 L 3.989 0 Z" fill="transparent"></path></svg>'
														}
														withExternalLayout={true}
													/>
												</SVG>
											</SVG>
										</motion.div>
										<motion.div
											className={"framer-do71ta"}
											layoutDependency={layoutDependency}
											layoutId={"YfwP6dCXd"}
											style={{
												backgroundColor:
													"var(--token-361e1224-4029-4612-a297-51f349511b71, rgba(255, 255, 255, 0.1))",
												borderBottomLeftRadius: 99,
												borderBottomRightRadius: 99,
												borderTopLeftRadius: 99,
												borderTopRightRadius: 99,
											}}
										>
											<SVG
												className={"framer-ev6qkb"}
												layoutDependency={layoutDependency}
												layoutId={"LK1TUtLw1"}
												opacity={1}
												requiresOverflowVisible={false}
												svg={
													'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11.862 8.918" overflow="visible"><g><g><defs><linearGradient id="idsLK1TUtLw1_2g92335677" x1="0" x2="1" y1="0.5172436927263692" y2="0.48275630727363084"><stop offset="0" stop-color="rgb(89,157,176)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(71,248,195)" stop-opacity="1"></stop></linearGradient></defs><path d="M 10.157 1.962 C 10.083 2.024 9.986 2.06 9.886 2.061 L 0.382 2.061 C 0.045 2.061 -0.126 1.704 0.108 1.495 L 1.669 0.103 C 1.741 0.038 1.838 0.002 1.939 0 L 11.48 0 C 11.821 0 11.988 0.36 11.751 0.57 Z" fill="url(#idsLK1TUtLw1_2g92335677)"></path></g><g><defs><linearGradient id="idsLK1TUtLw1_3g-674666400" x1="0" x2="1" y1="0.5140116233009214" y2="0.4859883766990786"><stop offset="0" stop-color="rgb(196,79,226)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(115,176,208)" stop-opacity="1"></stop></linearGradient></defs><path d="M 10.157 8.822 C 10.082 8.884 9.986 8.918 9.886 8.918 L 0.382 8.918 C 0.045 8.918 -0.126 8.565 0.108 8.356 L 1.669 6.96 C 1.742 6.896 1.838 6.86 1.939 6.861 L 11.48 6.861 C 11.821 6.861 11.988 7.218 11.751 7.426 Z" fill="url(#idsLK1TUtLw1_3g-674666400)"></path></g><g><defs><linearGradient id="idsLK1TUtLw1_4g1720462004" x1="0" x2="1" y1="0.4975124378109453" y2="0.5024875621890547"><stop offset="0" stop-color="rgb(119,140,191)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(93,205,201)" stop-opacity="1"></stop></linearGradient></defs><path d="M 10.157 3.528 C 10.082 3.466 9.986 3.432 9.886 3.432 L 0.382 3.432 C 0.045 3.432 -0.126 3.786 0.108 3.994 L 1.669 5.39 C 1.743 5.453 1.839 5.488 1.939 5.49 L 11.48 5.49 C 11.821 5.49 11.988 5.133 11.751 4.924 Z" fill="url(#idsLK1TUtLw1_4g1720462004)"></path></g></g></svg>'
												}
												withExternalLayout={true}
											>
												<SVG
													className={"framer-kuz4k8"}
													layoutDependency={layoutDependency}
													layoutId={"YeImSqkS2"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11.862 2.061" overflow="visible"><g><defs><linearGradient id="idsYeImSqkS2_1g92335677" x1="0" x2="1" y1="0.5172436927263692" y2="0.48275630727363084"><stop offset="0" stop-color="rgb(89,157,176)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(71,248,195)" stop-opacity="1"></stop></linearGradient></defs><path d="M 10.157 1.962 C 10.083 2.024 9.986 2.06 9.886 2.061 L 0.382 2.061 C 0.045 2.061 -0.126 1.704 0.108 1.495 L 1.669 0.103 C 1.741 0.038 1.838 0.002 1.939 0 L 11.48 0 C 11.821 0 11.988 0.36 11.751 0.57 Z" fill="url(#idsYeImSqkS2_1g92335677)"></path></g></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-twtp5u"}
													layoutDependency={layoutDependency}
													layoutId={"zuBjx3EdD"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11.862 2.058" overflow="visible"><g><defs><linearGradient id="idszuBjx3EdD_1g-674666400" x1="0" x2="1" y1="0.5140116233009214" y2="0.4859883766990786"><stop offset="0" stop-color="rgb(196,79,226)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(115,176,208)" stop-opacity="1"></stop></linearGradient></defs><path d="M 10.157 1.962 C 10.082 2.023 9.986 2.057 9.886 2.058 L 0.382 2.058 C 0.045 2.058 -0.126 1.704 0.108 1.495 L 1.669 0.099 C 1.742 0.035 1.838 0 1.939 0 L 11.48 0 C 11.821 0 11.988 0.357 11.751 0.566 Z" fill="url(#idszuBjx3EdD_1g-674666400)"></path></g></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-1kmzaf3"}
													layoutDependency={layoutDependency}
													layoutId={"XtLVB02HQ"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11.862 2.058" overflow="visible"><g><defs><linearGradient id="idsXtLVB02HQ_1g1720462004" x1="0" x2="1" y1="0.4975124378109453" y2="0.5024875621890547"><stop offset="0" stop-color="rgb(119,140,191)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(93,205,201)" stop-opacity="1"></stop></linearGradient></defs><path d="M 10.157 0.096 C 10.082 0.034 9.986 0 9.886 0 L 0.382 0 C 0.045 0 -0.126 0.354 0.108 0.562 L 1.669 1.958 C 1.743 2.021 1.839 2.056 1.939 2.058 L 11.48 2.058 C 11.821 2.058 11.988 1.701 11.751 1.492 Z" fill="url(#idsXtLVB02HQ_1g1720462004)"></path></g></svg>'
													}
													withExternalLayout={true}
												/>
											</SVG>
										</motion.div>
										<motion.div
											className={"framer-36g2z0"}
											layoutDependency={layoutDependency}
											layoutId={"RI7M5OJjo"}
											style={{
												backgroundColor:
													"var(--token-361e1224-4029-4612-a297-51f349511b71, rgba(255, 255, 255, 0.1))",
												borderBottomLeftRadius: 99,
												borderBottomRightRadius: 99,
												borderTopLeftRadius: 99,
												borderTopRightRadius: 99,
											}}
										>
											<Image
												background={{
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(20 +
																((componentViewport?.height || 141) -
																	40 -
																	282) /
																	2) +
															0 +
															0 +
															48 +
															0 +
															0,
													),
													pixelHeight: 32,
													pixelWidth: 32,
													src: "https://framerusercontent.com/images/CJkEJeGgzpwlhvouBoT5HMj0fE.svg?width=32&height=32",
												}}
												className={"framer-cs8vsr"}
												data-framer-name={"uni"}
												layoutDependency={layoutDependency}
												layoutId={"BSrGTRn6y"}
											/>
										</motion.div>
										<motion.div
											className={"framer-rmx12d"}
											layoutDependency={layoutDependency}
											layoutId={"UJ0_pSYQe"}
											style={{
												backgroundColor:
													"var(--token-361e1224-4029-4612-a297-51f349511b71, rgba(255, 255, 255, 0.1))",
												borderBottomLeftRadius: 99,
												borderBottomRightRadius: 99,
												borderTopLeftRadius: 99,
												borderTopRightRadius: 99,
											}}
										>
											<SVG
												className={"framer-12q36gr"}
												layoutDependency={layoutDependency}
												layoutId={"YUJKEdEzU"}
												opacity={1}
												requiresOverflowVisible={false}
												svg={
													'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16.16 7.896" overflow="visible"><path d="M 0.867 7.282 C 0.289 6.865 0 6.273 0 5.505 C 0.004 5.307 0.024 5.109 0.059 4.913 C 0.158 4.387 0.301 3.755 0.486 3.016 C 1.011 1.005 2.364 0 4.544 0 C 5.138 0 5.67 0.095 6.14 0.285 C 6.586 0.45 6.973 0.74 7.25 1.119 C 7.52 1.484 7.655 1.923 7.655 2.434 C 7.655 2.589 7.635 2.783 7.598 3.016 C 7.482 3.667 7.343 4.299 7.181 4.913 C 6.911 5.915 6.445 6.664 5.782 7.161 C 5.118 7.651 4.232 7.896 3.123 7.896 C 2.204 7.896 1.453 7.692 0.867 7.282 Z M 5.042 4.848 C 5.219 4.16 5.354 3.561 5.446 3.049 C 5.604 2.259 5.307 1.662 4.394 1.662 C 3.437 1.662 2.876 2.142 2.637 3.049 C 2.498 3.539 2.36 4.138 2.221 4.848 C 2.056 5.629 2.368 6.234 3.284 6.234 C 4.21 6.234 4.82 5.687 5.042 4.848 Z M 8.545 7.818 C 8.507 7.757 8.495 7.684 8.512 7.614 L 10.064 0.282 C 10.078 0.202 10.122 0.13 10.187 0.08 C 10.247 0.029 10.323 0.001 10.402 0 L 13.393 0 C 14.226 0 14.893 0.173 15.396 0.519 C 15.905 0.865 16.16 1.365 16.16 2.019 C 16.16 2.207 16.138 2.403 16.092 2.606 C 15.905 3.471 15.526 4.11 14.956 4.524 C 14.394 4.938 13.626 5.403 12.643 5.403 L 11.087 5.403 L 10.604 7.614 C 10.591 7.695 10.547 7.768 10.48 7.818 C 10.42 7.867 10.345 7.894 10.267 7.895 L 8.737 7.895 C 8.655 7.895 8.591 7.869 8.545 7.818 Z M 14.012 2.583 C 14.034 2.455 14.045 2.342 14.045 2.245 C 14.045 1.751 13.661 1.662 13.202 1.662 L 11.852 1.662 L 11.407 3.74 L 12.7 3.74 C 13.333 3.74 13.872 3.187 14.013 2.583 Z" fill="rgb(254,4,32)"></path></svg>'
												}
												withExternalLayout={true}
											>
												<SVG
													className={"framer-lfe0hq"}
													layoutDependency={layoutDependency}
													layoutId={"VH5WHi73W"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 7.655 7.896" overflow="visible"><path d="M 0.867 7.282 C 1.453 7.692 2.204 7.896 3.123 7.896 C 4.232 7.896 5.118 7.651 5.782 7.161 C 6.445 6.664 6.911 5.915 7.181 4.913 C 7.343 4.299 7.482 3.667 7.598 3.016 C 7.635 2.783 7.655 2.589 7.655 2.434 C 7.655 1.923 7.52 1.484 7.25 1.119 C 6.973 0.74 6.586 0.45 6.14 0.285 C 5.67 0.095 5.138 0 4.544 0 C 2.364 0 1.011 1.005 0.486 3.016 C 0.301 3.755 0.158 4.387 0.059 4.913 C 0.024 5.109 0.004 5.307 0 5.505 C 0 6.273 0.289 6.865 0.867 7.282" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-tifl2p"}
													layoutDependency={layoutDependency}
													layoutId={"oYUWLIS2y"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 3.308 4.572" overflow="visible"><path d="M 2.863 3.185 C 2.642 4.025 2.031 4.572 1.106 4.572 C 0.19 4.572 -0.123 3.967 0.042 3.185 C 0.181 2.476 0.32 1.877 0.459 1.387 C 0.697 0.48 1.259 0 2.215 0 C 3.128 0 3.426 0.597 3.268 1.387 C 3.175 1.899 3.04 2.498 2.863 3.185" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-5vba8u"}
													layoutDependency={layoutDependency}
													layoutId={"lDUw4kB1w"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 7.656 7.895" overflow="visible"><path d="M 0.041 7.818 C 0.087 7.869 0.15 7.895 0.233 7.895 L 1.763 7.895 C 1.841 7.894 1.916 7.867 1.976 7.818 C 2.042 7.768 2.087 7.695 2.1 7.614 L 2.583 5.403 L 4.139 5.403 C 5.121 5.403 5.889 4.938 6.452 4.524 C 7.022 4.11 7.401 3.471 7.588 2.606 C 7.634 2.403 7.656 2.207 7.656 2.019 C 7.656 1.365 7.401 0.865 6.891 0.519 C 6.389 0.173 5.721 0 4.889 0 L 1.897 0 C 1.819 0.001 1.743 0.029 1.683 0.08 C 1.618 0.13 1.574 0.202 1.56 0.282 L 0.007 7.614 C -0.009 7.684 0.003 7.757 0.041 7.818" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-6b59pa"}
													layoutDependency={layoutDependency}
													layoutId={"b4yv7SDgg"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2.638 2.078" overflow="visible"><path d="M 2.606 0.921 C 2.465 1.525 1.926 2.078 1.293 2.078 L 0 2.078 L 0.446 0 L 1.795 0 C 2.254 0 2.638 0.089 2.638 0.583 C 2.638 0.68 2.627 0.793 2.605 0.921" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
											</SVG>
										</motion.div>
										<motion.div
											className={"framer-1l4l02u"}
											layoutDependency={layoutDependency}
											layoutId={"r9Av_rct2"}
											style={{
												backgroundColor:
													"var(--token-361e1224-4029-4612-a297-51f349511b71, rgba(255, 255, 255, 0.1))",
												borderBottomLeftRadius: 99,
												borderBottomRightRadius: 99,
												borderTopLeftRadius: 99,
												borderTopRightRadius: 99,
											}}
										>
											<SVG
												className={"framer-7hojxj"}
												layoutDependency={layoutDependency}
												layoutId={"D6ykiRC3c"}
												opacity={1}
												requiresOverflowVisible={false}
												svg={
													'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 10.872 12.042" overflow="visible"><path d="M 2.1 1.843 L 5.436 0 L 8.773 1.843 L 7.55 2.525 L 5.436 1.361 L 3.327 2.524 Z M 8.773 4.171 L 7.55 3.489 L 5.436 4.652 L 3.327 3.489 L 2.101 4.171 L 2.101 5.532 L 4.207 6.697 L 4.207 9.021 L 5.437 9.703 L 6.663 9.021 L 6.663 6.697 L 8.774 5.532 Z M 8.773 7.86 L 8.773 6.497 L 7.55 7.179 L 7.55 8.54 Z M 9.646 8.342 L 7.536 9.502 L 7.536 10.868 L 10.872 9.021 L 10.872 5.335 L 9.646 6.014 Z M 8.419 3.008 L 9.643 3.69 L 9.643 5.051 L 10.872 4.372 L 10.872 3.008 L 9.646 2.325 L 8.419 3.011 Z M 4.207 9.999 L 4.207 11.36 L 5.436 12.042 L 6.663 11.36 L 6.663 10.001 L 5.436 10.68 L 4.21 9.998 Z M 2.1 7.858 L 3.323 8.54 L 3.323 7.179 L 2.1 6.496 L 2.1 7.862 Z M 4.207 3.008 L 5.436 3.689 L 6.663 3.007 L 5.436 2.324 L 4.21 3.01 Z M 1.226 3.69 L 2.453 3.008 L 1.23 2.325 L 0.001 3.011 L 0.001 4.374 L 1.226 5.053 Z M 1.226 6.014 L 0 5.335 L 0 9.022 L 3.337 10.868 L 3.337 9.5 L 1.23 8.339 L 1.23 6.011 Z" fill="rgb(240,185,11)"></path></svg>'
												}
												withExternalLayout={true}
											>
												<SVG
													className={"framer-o0bgea"}
													layoutDependency={layoutDependency}
													layoutId={"g8dPoFhZl"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 6.673 2.525" overflow="visible"><path d="M 0 1.843 L 3.336 0 L 6.673 1.843 L 5.45 2.525 L 3.336 1.361 L 1.227 2.524 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-17prhx1"}
													layoutDependency={layoutDependency}
													layoutId={"ndN6aSw3t"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 6.673 6.214" overflow="visible"><path d="M 6.672 0.682 L 5.449 0 L 3.335 1.164 L 1.226 0 L 0 0.682 L 0 2.043 L 2.106 3.208 L 2.106 5.532 L 3.336 6.214 L 4.563 5.532 L 4.563 3.208 L 6.673 2.043 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-19alq38"}
													layoutDependency={layoutDependency}
													layoutId={"nzd7m9MRo"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1.223 2.043" overflow="visible"><path d="M 1.223 1.364 L 1.223 0 L 0 0.682 L 0 2.043 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-1wpw18o"}
													layoutDependency={layoutDependency}
													layoutId={"ZmVmSUoGV"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 3.336 5.533" overflow="visible"><path d="M 2.11 3.007 L 0 4.168 L 0 5.533 L 3.336 3.686 L 3.336 0 L 2.11 0.679 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-1hkekec"}
													layoutDependency={layoutDependency}
													layoutId={"kzeaJehSU"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2.453 2.726" overflow="visible"><path d="M 0 0.683 L 1.223 1.365 L 1.223 2.726 L 2.453 2.047 L 2.453 0.683 L 1.226 0 L 0 0.686 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-1t1b6fc"}
													layoutDependency={layoutDependency}
													layoutId={"g7GgVMGf3"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2.456 2.044" overflow="visible"><path d="M 0 0.001 L 0 1.362 L 1.23 2.044 L 2.456 1.362 L 2.456 0.003 L 1.23 0.682 L 0.003 0 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-17d9r3c"}
													layoutDependency={layoutDependency}
													layoutId={"LStUdfuld"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1.223 2.044" overflow="visible"><path d="M 0 1.362 L 1.223 2.044 L 1.223 0.683 L 0 0 L 0 1.366 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-v4n611"}
													layoutDependency={layoutDependency}
													layoutId={"O83pE5zWM"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2.456 1.365" overflow="visible"><path d="M 0 0.684 L 1.23 1.365 L 2.456 0.683 L 1.23 0 L 0.003 0.686 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-1556j47"}
													layoutDependency={layoutDependency}
													layoutId={"By8tZKHl8"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2.452 2.728" overflow="visible"><path d="M 1.226 1.365 L 2.452 0.683 L 1.229 0 L 0 0.686 L 0 2.049 L 1.226 2.728 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
												<SVG
													className={"framer-uoz5r1"}
													layoutDependency={layoutDependency}
													layoutId={"myR8Yukbt"}
													opacity={1}
													requiresOverflowVisible={false}
													svg={
														'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 3.337 5.533" overflow="visible"><path d="M 1.226 0.679 L 0 0 L 0 3.686 L 3.337 5.533 L 3.337 4.165 L 1.23 3.003 L 1.23 0.675 Z" fill="transparent"></path></svg>'
													}
													withExternalLayout={true}
												/>
											</SVG>
										</motion.div>
									</motion.div>
								)}
								<RichText
									__fromCanvasComponent={true}
									className={"framer-h0gpgs"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"WQ40XB9IE"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											urpnMzLEm: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-c9mga6"}
															data-styles-preset={"Xa6VJQy2p"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))",
															}}
														>
															{"edit here"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-c9mga6"}
											data-styles-preset={"Xa6VJQy2p"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))",
											}}
										/>
									</React.Fragment>
								</RichText>
								<RichTextWithTruncateOneLineixo20j
									__fromCanvasComponent={true}
									className={"framer-ixo20j"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"TkpDVi92u"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={PHiMAXwcv}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-c9mga6"}
											data-styles-preset={"Xa6VJQy2p"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))",
											}}
										>
											{"+3 chains"}
										</motion.p>
									</React.Fragment>
								</RichTextWithTruncateOneLineixo20j>
							</motion.div>
							<motion.div
								className={"framer-1ju2bln"}
								layoutDependency={layoutDependency}
								layoutId={"prkAFWmLI"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1a21t6l"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"oroSOKuD_"}
									style={{
										"--extracted-gdpscs":
											"var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={lu3wTvpkh}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											className={"framer-styles-preset-90li6l"}
											data-styles-preset={"cgp7nxgQP"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-gdpscs, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))",
											}}
										>
											{"$109"}
										</motion.h1>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-8r73e6"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"DSbSV_0Gu"}
									style={{
										"--extracted-gdpscs":
											"var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={AtmCn84I2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											className={"framer-styles-preset-90li6l"}
											data-styles-preset={"cgp7nxgQP"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-gdpscs, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))",
											}}
										>
											{".52"}
										</motion.h1>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichTextWithTruncateOneLinexrq50f
								__fromCanvasComponent={true}
								className={"framer-xrq50f"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"l_6P11u5k"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={rpAaLLi6l}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-d4fts2"}
										data-styles-preset={"bRzBDjLMv"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)))",
										}}
									>
										{"+0.33% ($0.36) Today"}
									</motion.p>
								</React.Fragment>
							</RichTextWithTruncateOneLinexrq50f>
						</motion.div>
						<ComponentViewportProvider
							height={(componentViewport?.height || 141) * 1}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								((componentViewport?.height || 141) * 0.5045045045045047 -
									((componentViewport?.height || 141) * 1) / 2)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-q68u6r-container"}
								layoutDependency={layoutDependency}
								layoutId={"t0mNLW1LK-container"}
								nodeId={"t0mNLW1LK"}
								rendersWithMotion={true}
								scopeId={"rtwiOOpcU"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "t0mNLW1LK",
									layoutId: "t0mNLW1LK",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "CLljGfTtP",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-W83lO.framer-1d9nw51, .framer-W83lO .framer-1d9nw51 { display: block; }",
	".framer-W83lO.framer-1jbitbc { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px 16px 20px 16px; position: relative; width: 358px; }",
	".framer-W83lO .framer-xasvgc { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; z-index: 4; }",
	".framer-W83lO .framer-1qbzl4z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-W83lO .framer-ph3myg { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-W83lO .framer-cbce4z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
	".framer-W83lO .framer-clyb9h, .framer-W83lO .framer-do71ta, .framer-W83lO .framer-36g2z0, .framer-W83lO .framer-rmx12d, .framer-W83lO .framer-1l4l02u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 24px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 24px; will-change: var(--framer-will-change-override, transform); }",
	".framer-W83lO .framer-mnsxf4 { height: 14px; position: relative; width: 9px; }",
	".framer-W83lO .framer-15qrl3x { height: 7px; left: 5px; position: absolute; top: 0px; width: 5px; }",
	".framer-W83lO .framer-cibkwa { height: 7px; left: 0px; position: absolute; top: 0px; width: 5px; }",
	".framer-W83lO .framer-1lq1r84 { height: 6px; left: 5px; position: absolute; top: 8px; width: 5px; }",
	".framer-W83lO .framer-4bv7jq { height: 6px; left: 0px; position: absolute; top: 8px; width: 5px; }",
	".framer-W83lO .framer-w7d0za { height: 5px; left: 5px; position: absolute; top: 5px; width: 5px; }",
	".framer-W83lO .framer-a8n6rb { height: 5px; left: 0px; position: absolute; top: 5px; width: 5px; }",
	".framer-W83lO .framer-kkdaxr, .framer-W83lO .framer-1e4472v { height: 10px; left: 0px; position: absolute; top: 0px; width: 9px; }",
	".framer-W83lO .framer-1avndow { height: 7px; left: 1px; position: absolute; top: 1px; width: 4px; }",
	".framer-W83lO .framer-14mtm2k { height: 4px; left: 0px; position: absolute; top: 6px; width: 5px; }",
	".framer-W83lO .framer-l8xq3l { height: 4px; left: 5px; position: absolute; top: 6px; width: 5px; }",
	".framer-W83lO .framer-1nnc3nk { height: 7px; left: 5px; position: absolute; top: 1px; width: 4px; }",
	".framer-W83lO .framer-vtha3w { height: 6px; left: 0px; position: absolute; top: 5px; width: 9px; }",
	".framer-W83lO .framer-1gpw75u { height: 6px; left: 0px; position: absolute; top: 0px; width: 9px; }",
	".framer-W83lO .framer-of7sfx { height: 6px; left: 1px; position: absolute; top: 1px; width: 4px; }",
	".framer-W83lO .framer-1bwy0aj { height: 6px; left: 5px; position: absolute; top: 1px; width: 4px; }",
	".framer-W83lO .framer-ev6qkb { height: 9px; position: relative; width: 12px; }",
	".framer-W83lO .framer-kuz4k8 { height: 2px; left: 0px; position: absolute; top: 0px; width: 12px; }",
	".framer-W83lO .framer-twtp5u { height: 2px; left: 0px; position: absolute; top: 7px; width: 12px; }",
	".framer-W83lO .framer-1kmzaf3 { height: 2px; left: 0px; position: absolute; top: 4px; width: 12px; }",
	".framer-W83lO .framer-cs8vsr { flex: none; height: 24px; position: relative; width: 24px; }",
	".framer-W83lO .framer-12q36gr { height: 8px; position: relative; width: 16px; }",
	".framer-W83lO .framer-lfe0hq { height: 8px; left: 0px; position: absolute; top: 0px; width: 8px; }",
	".framer-W83lO .framer-tifl2p { height: 5px; left: 2px; position: absolute; top: 2px; width: 4px; }",
	".framer-W83lO .framer-5vba8u { height: 8px; left: 9px; position: absolute; top: 0px; width: 8px; }",
	".framer-W83lO .framer-6b59pa { height: 2px; left: 12px; position: absolute; top: 2px; width: 3px; }",
	".framer-W83lO .framer-7hojxj { height: 12px; position: relative; width: 11px; }",
	".framer-W83lO .framer-o0bgea { height: 3px; left: 2px; position: absolute; top: 0px; width: 7px; }",
	".framer-W83lO .framer-17prhx1 { height: 6px; left: 2px; position: absolute; top: 4px; width: 7px; }",
	".framer-W83lO .framer-19alq38 { height: 2px; left: 8px; position: absolute; top: 7px; width: 1px; }",
	".framer-W83lO .framer-1wpw18o { height: 6px; left: 8px; position: absolute; top: 6px; width: 4px; }",
	".framer-W83lO .framer-1hkekec { height: 3px; left: 9px; position: absolute; top: 3px; width: 3px; }",
	".framer-W83lO .framer-1t1b6fc { height: 2px; left: 4px; position: absolute; top: 10px; width: 3px; }",
	".framer-W83lO .framer-17d9r3c { height: 2px; left: 2px; position: absolute; top: 7px; width: 1px; }",
	".framer-W83lO .framer-v4n611 { height: 2px; left: 4px; position: absolute; top: 3px; width: 3px; }",
	".framer-W83lO .framer-1556j47 { height: 3px; left: 0px; position: absolute; top: 3px; width: 3px; }",
	".framer-W83lO .framer-uoz5r1 { height: 6px; left: 0px; position: absolute; top: 6px; width: 4px; }",
	".framer-W83lO .framer-h0gpgs, .framer-W83lO .framer-ixo20j { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-W83lO .framer-1ju2bln { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-W83lO .framer-1a21t6l { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-W83lO .framer-8r73e6 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-W83lO .framer-xrq50f { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-W83lO .framer-q68u6r-container { -webkit-user-select: none; flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); pointer-events: none; position: absolute; top: calc(50.45045045045047% - 100% / 2); user-select: none; width: 100%; z-index: 2; }",
	...css2,
	...css,
	...css3,
	'.framer-W83lO[data-border="true"]::after, .framer-W83lO [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerrtwiOOpcU = withCSS(Component, css4, "framer-W83lO");
var stdin_default2 = FramerrtwiOOpcU;
FramerrtwiOOpcU.displayName = "PortfolioCard";
FramerrtwiOOpcU.defaultProps = {
	height: 141,
	width: 358,
};
addPropertyControls(FramerrtwiOOpcU, {
	variant: {
		options: ["bwNMSxDqZ", "urpnMzLEm"],
		optionTitles: ["Desktop", "real"],
		title: "Variant",
		type: ControlType.Enum,
	},
	lu3wTvpkh: {
		defaultValue: "$109",
		displayTextArea: false,
		title: "price1",
		type: ControlType.String,
	},
	AtmCn84I2: {
		defaultValue: ".52",
		displayTextArea: false,
		title: "price2",
		type: ControlType.String,
	},
	PHiMAXwcv: {
		defaultValue: "+3 chains",
		displayTextArea: false,
		title: "chainCount",
		type: ControlType.String,
	},
	rpAaLLi6l: {
		defaultValue: "+0.33% ($0.36) Today",
		displayTextArea: false,
		title: "diff",
		type: ControlType.String,
	},
});
addFonts(
	FramerrtwiOOpcU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MainSiteGridBorderFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:portfolio-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "bwNMSxDqZ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PortfolioCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var portfolio_card_default = ComponentWithRoot;
export { portfolio_card_default as default };
