// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c32b11589f2bc68b "humanpass", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'connected' | 'twitter' | 'telegram' | 'farcaster' // Variant
 * twitterHandle?: string // twitterHandle
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-IPS3SQC7.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-OUEV7UWA.js";
import { stdin_default } from "./chunks/chunk-U6SQYF76.js";
import "./chunks/chunk-R527CHIA.js";
import { routes } from "./chunks/chunk-QMBC2E5Z.js";
import "./chunks/chunk-WSFCRVEQ.js";

// virtual:social-account-item
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/OHflKOCQMR1MjQ2QbAzK/dTJqOZDABftP2chcf55F/YyGh9D7uE.js
import { jsx as _jsx4, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls5,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType5,
	cx as cx4,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	SVG as SVG3,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS4,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion4,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/qjdqd1Ujhe2h81P7f6x3/032cly3ueitT8YyiTo3q/EVK7RjOjy.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 5.999 9.643 L 19.444 0.007 C 19.421 -0.002 19.394 -0.002 19.371 0.007 L 0.374 7.441 C 0.132 7.534 -0.02 7.776 0.002 8.035 C 0.024 8.293 0.214 8.507 0.468 8.558 L 5.999 9.643" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="9.643048607200637px" id="f0Sepis6b" transform="translate(1.501 3.001)" width="19.443967614765597px"/><path d="M 4.16 3.648 L 1.29 6.625 C 1.078 6.845 0.753 6.915 0.47 6.801 C 0.186 6.686 0 6.412 0 6.106 L 0 0 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="6.85485784807608px" id="JjRxJUDRo" transform="translate(7.5 12.644)" width="4.159687500000004px"/><path d="M 5.999 9.644 L 14.461 17.062 C 14.659 17.237 14.935 17.295 15.187 17.214 C 15.439 17.133 15.629 16.925 15.688 16.668 L 19.499 0.114 C 19.507 0.08 19.495 0.045 19.469 0.023 C 19.443 0 19.406 -0.006 19.374 0.006 L 0.374 7.442 C 0.132 7.535 -0.02 7.777 0.002 8.036 C 0.024 8.294 0.214 8.508 0.468 8.559 Z" fill="transparent" height="17.249981612497756px" id="aDGI3ebx1" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(1.501 3)" width="19.501551906886707px"/><path d="M 0 9.636 L 13.445 0" fill="transparent" height="9.635625000000001px" id="LuuR56ReO" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(7.5 3.008)" width="13.4446875px"/><path d="M 4.16 3.648 L 1.29 6.625 C 1.078 6.845 0.753 6.915 0.47 6.801 C 0.186 6.686 0 6.412 0 6.106 L 0 0" fill="transparent" height="6.85485784807608px" id="ptXTSdC_s" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(7.5 12.644)" width="4.159687500000004px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className5,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("2921807503", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-DjU2n", className5)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css3 = [
	`.framer-DjU2n { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css3, "framer-DjU2n");
Icon.displayName = "Telegram Logo";
var stdin_default2 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/h8vhsG9EX66OBSmE3HMp/kzm3724QBOuwaxzn8Fbg/xQdZ83E_u.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion2.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps2 = ({ color, height, id, width, ...props }) => {
	return {
		...props,
		uzX9aY7lz: color ?? props.uzX9aY7lz ?? "rgb(255, 255, 255)",
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className5,
		layoutId,
		variant,
		uzX9aY7lz,
		...restProps
	} = getProps2(props);
	return (
		<SVG2
			{...restProps}
			className={cx2("framer-CrXR6", className5)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--1ya7007": uzX9aY7lz,
				...style,
			}}
		/>
	);
});
var css4 = [
	`.framer-CrXR6 { aspect-ratio: 1; background-color: var(--1ya7007); mask-image: url('data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><g d="M 17.382 0 L 20.754 0 L 13.35 8.487 L 22 20 L 15.212 20 L 9.897 13.004 L 3.812 20 L 0.44 20 L 8.284 10.923 L 0 0 L 6.957 0 L 11.759 6.391 Z M 16.201 18.007 L 18.071 18.007 L 5.975 1.919 L 3.966 1.919 Z" fill="transparent" height="20px" id="bbL0Z3alC" transform="translate(1 2)" width="22px"><path d="M 17.382 0 L 20.754 0 L 13.35 8.487 L 22 20 L 15.212 20 L 9.897 13.004 L 3.812 20 L 0.44 20 L 8.284 10.923 L 0 0 L 6.957 0 L 11.759 6.391 Z M 16.201 18.007 L 18.071 18.007 L 5.975 1.919 L 3.966 1.919 Z" fill="var(--1ya7007, rgb(255,255,255))" height="20px" id="SuhZcFJlk" width="22px"/></g></svg>'); mask-position: center; mask-repeat: no-repeat; width: 24px; }`,
];
var Icon2 = withCSS2(Component2, css4, "framer-CrXR6");
var stdin_default3 = Icon2;
addPropertyControls2(Icon2, {
	uzX9aY7lz: {
		defaultValue: "rgb(255, 255, 255)",
		hidden: false,
		title: "Color",
		type: ControlType2.Color,
	},
});

// /:https://framerusercontent.com/modules/dQZOS00ARXstCRjr6iYz/g3K3Ulq70TtS0U9REaM0/xN9fPUCLr.js
import {
	jsx as _jsx3,
	jsxs as _jsxs2,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls4,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType as ControlType4,
	cx as cx3,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	PathVariablesContext,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useQueryData as useQueryData2,
	useVariantState,
	withCSS as withCSS3,
} from "unframer";
import { LayoutGroup, motion as motion3, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/7xgQ9SoOXd63nxx7audl/RDg2ik6BnQhb3UPwnJ3v/CMSCounter.js
import { jsxs as _jsxs } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	RenderTarget,
	useQueryData,
} from "unframer";

// /:https://framer.com/m/CMSLibrary-09eo.js
function getCollectionData(collectionList) {
	var _collectionList_props,
		_collectionList_props_children_props,
		_collectionList_props_children,
		_collectionList_props1,
		_collectionList_props_children_props_children_props,
		_collectionList_props_children_props_children,
		_collectionList_props_children_props1,
		_collectionList_props_children1,
		_collectionList_props2,
		_queryParent_props;
	let queryParent = null;
	if (
		collectionList === null || collectionList === void 0
			? void 0
			: (_collectionList_props = collectionList.props) === null ||
					_collectionList_props === void 0
				? void 0
				: _collectionList_props.query
	) {
		queryParent = collectionList;
	} else if (
		collectionList === null || collectionList === void 0
			? void 0
			: (_collectionList_props1 = collectionList.props) === null ||
					_collectionList_props1 === void 0
				? void 0
				: (_collectionList_props_children = _collectionList_props1.children) ===
							null || _collectionList_props_children === void 0
					? void 0
					: (_collectionList_props_children_props =
								_collectionList_props_children.props) === null ||
							_collectionList_props_children_props === void 0
						? void 0
						: _collectionList_props_children_props.query
	) {
		queryParent = collectionList.props.children;
	} else if (
		collectionList === null || collectionList === void 0
			? void 0
			: (_collectionList_props2 = collectionList.props) === null ||
					_collectionList_props2 === void 0
				? void 0
				: (_collectionList_props_children1 =
							_collectionList_props2.children) === null ||
						_collectionList_props_children1 === void 0
					? void 0
					: (_collectionList_props_children_props1 =
								_collectionList_props_children1.props) === null ||
							_collectionList_props_children_props1 === void 0
						? void 0
						: (_collectionList_props_children_props_children =
									_collectionList_props_children_props1.children) === null ||
								_collectionList_props_children_props_children === void 0
							? void 0
							: (_collectionList_props_children_props_children_props =
										_collectionList_props_children_props_children.props) ===
										null ||
									_collectionList_props_children_props_children_props === void 0
								? void 0
								: _collectionList_props_children_props_children_props.query
	) {
		queryParent = collectionList.props.children.props.children;
	}
	const query =
		queryParent === null || queryParent === void 0
			? void 0
			: (_queryParent_props = queryParent.props) === null ||
					_queryParent_props === void 0
				? void 0
				: _queryParent_props.query;
	let queryData = null;
	if (query === null || query === void 0 ? void 0 : query.from) {
		if (query.from.data) {
			queryData = query.from.data;
		} else if (query.from.left) {
			let left = query.from.left;
			for (let i3 = 0; i3 < 100; i3++) {
				if (left.type == "Collection") {
					queryData = left.data;
					break;
				} else if (left.left) {
					left = left.left;
				} else {
					break;
				}
			}
		}
	}
	const propertyControlsById =
		(queryData === null || queryData === void 0
			? void 0
			: queryData.propertyControls) || {};
	const propertyControlsByName = {};
	for (const id in propertyControlsById) {
		const control = propertyControlsById[id];
		propertyControlsByName[control.title] = {
			id,
			...control,
		};
	}
	let childrenFunction = null;
	if (collectionList) {
		var _collectionList_props3,
			_clpc_props,
			_clpc_props_children_props,
			_clpc_props_children,
			_clpc_props1;
		const clpc =
			(_collectionList_props3 = collectionList.props) === null ||
			_collectionList_props3 === void 0
				? void 0
				: _collectionList_props3.children;
		if (typeof clpc == "function") {
			childrenFunction = clpc;
		} else if (
			typeof (clpc === null || clpc === void 0
				? void 0
				: (_clpc_props = clpc.props) === null || _clpc_props === void 0
					? void 0
					: _clpc_props.children) == "function"
		) {
			childrenFunction = clpc.props.children;
		} else if (
			typeof (clpc === null || clpc === void 0
				? void 0
				: (_clpc_props1 = clpc.props) === null || _clpc_props1 === void 0
					? void 0
					: (_clpc_props_children = _clpc_props1.children) === null ||
							_clpc_props_children === void 0
						? void 0
						: (_clpc_props_children_props = _clpc_props_children.props) ===
									null || _clpc_props_children_props === void 0
							? void 0
							: _clpc_props_children_props.children) == "function"
		) {
			childrenFunction = clpc.props.children.props.children;
		}
	}
	return {
		query,
		queryParent,
		queryData,
		propertyControlsById,
		propertyControlsByName,
		childrenFunction,
	};
}

// /:https://framerusercontent.com/modules/7xgQ9SoOXd63nxx7audl/RDg2ik6BnQhb3UPwnJ3v/CMSCounter.js
function formatNumber(value, commas) {
	let numberString = value.toFixed(0);
	if (commas) {
		numberString = numberString.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
	}
	return numberString;
}
function CMSCounter(props) {
	const { transform } = props;
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const collectionList = props.collectionList?.[0];
	const { query } = getCollectionData(collectionList);
	let items = props.placeholder;
	if (query && !isCanvas) {
		items = useQueryData(query).length;
	}
	let prefix = "";
	let suffix = "";
	if (transform) {
		if (transform.plural) {
			prefix = items === 1 ? transform.singularPrefix : transform.pluralPrefix;
			suffix = items === 1 ? transform.singularSuffix : transform.pluralSuffix;
		} else {
			prefix = transform.prefix;
			suffix = transform.suffix;
		}
	}
	return (
		<div
			style={{
				color: props.fontColor,
				userSelect: props.textSelect ? "auto" : "none",
				margin: 0,
				whiteSpace: props.style?.width ? void 0 : "nowrap",
				...props.font,
				...props.style,
			}}
		>
			{prefix}
			{formatNumber(items, props.commas)}
			{suffix}
		</div>
	);
}
CMSCounter.displayName = "CMS Item Counter";
addPropertyControls3(CMSCounter, {
	collectionList: {
		type: ControlType3.ComponentInstance,
	},
	placeholder: {
		type: ControlType3.Number,
		defaultValue: 10,
		min: 0,
		step: 1,
		description: "Placeholder number is shown in the editor.",
	},
	commas: {
		type: ControlType3.Boolean,
		defaultValue: true,
	},
	fontColor: {
		type: ControlType3.Color,
		defaultValue: "#000",
	},
	font: {
		type: "font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: 14,
			lineHeight: 1,
		},
	},
	transform: {
		type: ControlType3.Object,
		optional: true,
		controls: {
			plural: {
				type: ControlType3.Boolean,
				defaultValue: false,
				enabledTitle: "On",
				disabledTitle: "Off",
			},
			prefix: {
				type: ControlType3.String,
				hidden(props) {
					return props.plural;
				},
			},
			suffix: {
				type: ControlType3.String,
				hidden(props) {
					return props.plural;
				},
			},
			singularPrefix: {
				type: ControlType3.String,
				placeholder: "Singular Prefix",
				hidden(props) {
					return !props.plural;
				},
			},
			singularSuffix: {
				type: ControlType3.String,
				placeholder: "Singular Suffix",
				hidden(props) {
					return !props.plural;
				},
			},
			pluralPrefix: {
				type: ControlType3.String,
				placeholder: "Plural Prefix",
				hidden(props) {
					return !props.plural;
				},
			},
			pluralSuffix: {
				type: ControlType3.String,
				placeholder: "Plural Suffix",
				hidden(props) {
					return !props.plural;
				},
			},
		},
	},
	textSelect: {
		type: ControlType3.Boolean,
		defaultValue: true,
	},
});

// /:https://framerusercontent.com/modules/g0Nz5LZJx3cYVkiD7uS1/JGIdW4ek1nGSKkTT9gya/FQ9Fz288R.js
import {
	addPropertyControls as e4,
	ControlType as t4,
	QueryCache as l2,
	QueryEngine as i2,
} from "unframer";

// /:https://framerusercontent.com/modules/g0Nz5LZJx3cYVkiD7uS1/JGIdW4ek1nGSKkTT9gya/FQ9Fz288R-0.js
import { ControlType as v } from "unframer";
import { ControlType as x } from "unframer";
var t;
var e = Object.create;
var r = Object.defineProperty;
var n = Object.getOwnPropertyDescriptor;
var i = Object.getOwnPropertyNames;
var s = Object.getPrototypeOf;
var a = Object.prototype.hasOwnProperty;
var o = (t32, e42, n22) =>
	e42 in t32
		? r(t32, e42, {
				enumerable: true,
				configurable: true,
				writable: true,
				value: n22,
			})
		: (t32[e42] = n22);
var u = (t32, e42) =>
	function () {
		return (
			e42 ||
				(0, t32[i(t32)[0]])(
					(e42 = {
						exports: {},
					}).exports,
					e42,
				),
			e42.exports
		);
	};
var l = (t32, e42, s2, o22) => {
	if ((e42 && "object" == typeof e42) || "function" == typeof e42)
		for (let u22 of i(e42))
			a.call(t32, u22) ||
				u22 === s2 ||
				r(t32, u22, {
					get: () => e42[u22],
					enumerable: !(o22 = n(e42, u22)) || o22.enumerable,
				});
	return t32;
};
var h = (t32, n22, i22) => (
	(i22 = null != t32 ? e(s(t32)) : {}),
	l(
		// If the importer is in node compatibility mode or this is not an ESM
		// file that has been converted to a CommonJS file using a Babel-
		// compatible transform (i.e. "__esModule" has not been set), then set
		// "default" to the CommonJS "module.exports" for node compatibility.
		!n22 && t32 && t32.__esModule
			? i22
			: r(i22, "default", {
					value: t32,
					enumerable: true,
				}),
		t32,
	)
);
var c = (t32, e42, r22) => o(t32, "symbol" != typeof e42 ? e42 + "" : e42, r22);
var f = u({
	"../../../node_modules/dataloader/index.js"(t32, e42) {
		var r22,
			n22 = /* @__PURE__ */ (function () {
				function t42(t5, e6) {
					if ("function" != typeof t5)
						throw TypeError(
							"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but got: " +
								t5 +
								".",
						);
					(this._batchLoadFn = t5),
						(this._maxBatchSize = (function (t6) {
							if (!(!t6 || false !== t6.batch)) return 1;
							var e7 = t6 && t6.maxBatchSize;
							if (void 0 === e7) return 1 / 0;
							if ("number" != typeof e7 || e7 < 1)
								throw TypeError(
									"maxBatchSize must be a positive number: " + e7,
								);
							return e7;
						})(e6)),
						(this._batchScheduleFn = (function (t6) {
							var e7 = t6 && t6.batchScheduleFn;
							if (void 0 === e7) return i22;
							if ("function" != typeof e7)
								throw TypeError("batchScheduleFn must be a function: " + e7);
							return e7;
						})(e6)),
						(this._cacheKeyFn = (function (t6) {
							var e7 = t6 && t6.cacheKeyFn;
							if (void 0 === e7)
								return function (t7) {
									return t7;
								};
							if ("function" != typeof e7)
								throw TypeError("cacheKeyFn must be a function: " + e7);
							return e7;
						})(e6)),
						(this._cacheMap = (function (t6) {
							if (!(!t6 || false !== t6.cache)) return null;
							var e7 = t6 && t6.cacheMap;
							if (void 0 === e7) return /* @__PURE__ */ new Map();
							if (null !== e7) {
								var r3 = ["get", "set", "delete", "clear"].filter(
									function (t7) {
										return e7 && "function" != typeof e7[t7];
									},
								);
								if (0 !== r3.length)
									throw TypeError(
										"Custom cacheMap missing methods: " + r3.join(", "),
									);
							}
							return e7;
						})(e6)),
						(this._batch = null),
						(this.name = e6 && e6.name ? e6.name : null);
				}
				var e5 = t42.prototype;
				return (
					(e5.load = function (t5) {
						if (null == t5)
							throw TypeError(
								"The loader.load() function must be called with a value, but got: " +
									String(t5) +
									".",
							);
						var e6 = (function (t6) {
								var e7 = t6._batch;
								if (
									null !== e7 &&
									!e7.hasDispatched &&
									e7.keys.length < t6._maxBatchSize
								)
									return e7;
								var r4 = {
									hasDispatched: false,
									keys: [],
									callbacks: [],
								};
								return (
									(t6._batch = r4),
									t6._batchScheduleFn(function () {
										(function (t7, e8) {
											var r5;
											if (((e8.hasDispatched = true), 0 === e8.keys.length)) {
												a2(e8);
												return;
											}
											try {
												r5 = t7._batchLoadFn(e8.keys);
											} catch (r6) {
												return s2(
													t7,
													e8,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function errored synchronously: " +
															String(r6) +
															".",
													),
												);
											}
											if (!r5 || "function" != typeof r5.then)
												return s2(
													t7,
													e8,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise: " +
															String(r5) +
															".",
													),
												);
											r5.then(function (t8) {
												if (!o22(t8))
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array: " +
															String(t8) +
															".",
													);
												if (t8.length !== e8.keys.length)
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\n" +
															String(e8.keys) +
															"\n\nValues:\n" +
															String(t8),
													);
												a2(e8);
												for (var r6 = 0; r6 < e8.callbacks.length; r6++) {
													var n4 = t8[r6];
													n4 instanceof Error
														? e8.callbacks[r6].reject(n4)
														: e8.callbacks[r6].resolve(n4);
												}
											}).catch(function (r6) {
												s2(t7, e8, r6);
											});
										})(t6, r4);
									}),
									r4
								);
							})(this),
							r3 = this._cacheMap,
							n3 = this._cacheKeyFn(t5);
						if (r3) {
							var i3 = r3.get(n3);
							if (i3) {
								var u22 = e6.cacheHits || (e6.cacheHits = []);
								return new Promise(function (t6) {
									u22.push(function () {
										t6(i3);
									});
								});
							}
						}
						e6.keys.push(t5);
						var l22 = new Promise(function (t6, r4) {
							e6.callbacks.push({
								resolve: t6,
								reject: r4,
							});
						});
						return r3 && r3.set(n3, l22), l22;
					}),
					(e5.loadMany = function (t5) {
						if (!o22(t5))
							throw TypeError(
								"The loader.loadMany() function must be called with Array<key> but got: " +
									t5 +
									".",
							);
						for (var e6 = [], r3 = 0; r3 < t5.length; r3++)
							e6.push(
								this.load(t5[r3]).catch(function (t6) {
									return t6;
								}),
							);
						return Promise.all(e6);
					}),
					(e5.clear = function (t5) {
						var e6 = this._cacheMap;
						if (e6) {
							var r3 = this._cacheKeyFn(t5);
							e6.delete(r3);
						}
						return this;
					}),
					(e5.clearAll = function () {
						var t5 = this._cacheMap;
						return t5 && t5.clear(), this;
					}),
					(e5.prime = function (t5, e6) {
						var r3 = this._cacheMap;
						if (r3) {
							var n3,
								i3 = this._cacheKeyFn(t5);
							void 0 === r3.get(i3) &&
								(e6 instanceof Error
									? (n3 = Promise.reject(e6)).catch(function () {})
									: (n3 = Promise.resolve(e6)),
								r3.set(i3, n3));
						}
						return this;
					}),
					t42
				);
			})(),
			i22 =
				"object" == typeof process && "function" == typeof process.nextTick
					? function (t42) {
							r22 || (r22 = Promise.resolve()),
								r22.then(function () {
									process.nextTick(t42);
								});
						}
					: "function" == typeof setImmediate
						? function (t42) {
								setImmediate(t42);
							}
						: function (t42) {
								setTimeout(t42);
							};
		function s2(t42, e5, r3) {
			a2(e5);
			for (var n3 = 0; n3 < e5.keys.length; n3++)
				t42.clear(e5.keys[n3]), e5.callbacks[n3].reject(r3);
		}
		function a2(t42) {
			if (t42.cacheHits)
				for (var e5 = 0; e5 < t42.cacheHits.length; e5++) t42.cacheHits[e5]();
		}
		function o22(t42) {
			return (
				"object" == typeof t42 &&
				null !== t42 &&
				"number" == typeof t42.length &&
				(0 === t42.length ||
					(t42.length > 0 &&
						Object.prototype.hasOwnProperty.call(t42, t42.length - 1)))
			);
		}
		e42.exports = n22;
	},
});
var g = h(f());
var d = {
	Uint8: 1,
	Uint16: 2,
	Uint32: 4,
	BigUint64: 8,
	Int8: 1,
	Int16: 2,
	Int32: 4,
	BigInt64: 8,
	Float32: 4,
	Float64: 8,
};
var y = class {
	getOffset() {
		return this.offset;
	}
	ensureLength(t32) {
		let e42 = this.bytes.length;
		if (!(this.offset + t32 <= e42)) throw Error("Reading out of bounds");
	}
	readUint8() {
		let t32 = d.Uint8;
		this.ensureLength(t32);
		let e42 = this.view.getUint8(this.offset);
		return (this.offset += t32), e42;
	}
	readUint16() {
		let t32 = d.Uint16;
		this.ensureLength(t32);
		let e42 = this.view.getUint16(this.offset);
		return (this.offset += t32), e42;
	}
	readUint32() {
		let t32 = d.Uint32;
		this.ensureLength(t32);
		let e42 = this.view.getUint32(this.offset);
		return (this.offset += t32), e42;
	}
	readUint64() {
		let t32 = this.readBigUint64();
		return Number(t32);
	}
	readBigUint64() {
		let t32 = d.BigUint64;
		this.ensureLength(t32);
		let e42 = this.view.getBigUint64(this.offset);
		return (this.offset += t32), e42;
	}
	readInt8() {
		let t32 = d.Int8;
		this.ensureLength(t32);
		let e42 = this.view.getInt8(this.offset);
		return (this.offset += t32), e42;
	}
	readInt16() {
		let t32 = d.Int16;
		this.ensureLength(t32);
		let e42 = this.view.getInt16(this.offset);
		return (this.offset += t32), e42;
	}
	readInt32() {
		let t32 = d.Int32;
		this.ensureLength(t32);
		let e42 = this.view.getInt32(this.offset);
		return (this.offset += t32), e42;
	}
	readInt64() {
		let t32 = this.readBigInt64();
		return Number(t32);
	}
	readBigInt64() {
		let t32 = d.BigInt64;
		this.ensureLength(t32);
		let e42 = this.view.getBigInt64(this.offset);
		return (this.offset += t32), e42;
	}
	readFloat32() {
		let t32 = d.Float32;
		this.ensureLength(t32);
		let e42 = this.view.getFloat32(this.offset);
		return (this.offset += t32), e42;
	}
	readFloat64() {
		let t32 = d.Float64;
		this.ensureLength(t32);
		let e42 = this.view.getFloat64(this.offset);
		return (this.offset += t32), e42;
	}
	readBytes(t32) {
		let e42 = this.offset,
			r22 = e42 + t32,
			n22 = this.bytes.subarray(e42, r22);
		return (this.offset = r22), n22;
	}
	readString() {
		let t32 = this.readUint32(),
			e42 = this.readBytes(t32);
		return this.decoder.decode(e42);
	}
	readJson() {
		let t32 = this.readString();
		return JSON.parse(t32);
	}
	constructor(t32) {
		(this.bytes = t32),
			c(this, "offset", 0),
			c(this, "view"),
			c(this, "decoder", new TextDecoder()),
			(this.view = p(this.bytes));
	}
};
function p(t32) {
	return new DataView(t32.buffer, t32.byteOffset, t32.byteLength);
}
var m = "undefined" != typeof window;
var w = m && "function" == typeof window.requestIdleCallback;
function I(t32, ...e42) {
	if (!t32)
		throw Error(
			"Assertion Error" + (e42.length > 0 ? ": " + e42.join(" ") : ""),
		);
}
function b(t32) {
	throw Error(`Unexpected value: ${t32}`);
}
var k = (t32) => 2 ** t32 - 1;
var L = (t32) => -(2 ** (t32 - 1));
var B = (t32) => 2 ** (t32 - 1) - 1;
var E = {
	Uint8: 0,
	Uint16: 0,
	Uint32: 0,
	Uint64: 0,
	BigUint64: 0,
	Int8: L(8),
	Int16: L(16),
	Int32: L(32),
	Int64: Number.MIN_SAFE_INTEGER,
	BigInt64: -(BigInt(2) ** BigInt(63)),
};
var M = {
	Uint8: k(8),
	Uint16: k(16),
	Uint32: k(32),
	Uint64: Number.MAX_SAFE_INTEGER,
	BigUint64: BigInt(2) ** BigInt(64) - BigInt(1),
	Int8: B(8),
	Int16: B(16),
	Int32: B(32),
	Int64: Number.MAX_SAFE_INTEGER,
	BigInt64: BigInt(2) ** BigInt(63) - BigInt(1),
};
function N(t32) {
	return Number.isFinite(t32);
}
function A(t32) {
	return null === t32;
}
var O = class t2 {
	static fromString(e42) {
		let [r22, n22, i22] = e42.split("/").map(Number);
		return (
			I(N(r22), "Invalid chunkId"),
			I(N(n22), "Invalid offset"),
			I(N(i22), "Invalid length"),
			new t2(r22, n22, i22)
		);
	}
	toString() {
		return `${this.chunkId}/${this.offset}/${this.length}`;
	}
	static read(e42) {
		let r22 = e42.readUint16(),
			n22 = e42.readUint32(),
			i22 = e42.readUint32();
		return new t2(r22, n22, i22);
	}
	write(t32) {
		t32.writeUint16(this.chunkId),
			t32.writeUint32(this.offset),
			t32.writeUint32(this.length);
	}
	compare(t32) {
		return this.chunkId < t32.chunkId
			? -1
			: this.chunkId > t32.chunkId
				? 1
				: this.offset < t32.offset
					? -1
					: this.offset > t32.offset
						? 1
						: (I(this.length === t32.length), 0);
	}
	constructor(t32, e42, r22) {
		(this.chunkId = t32), (this.offset = e42), (this.length = r22);
	}
};
function P(t32) {
	if (A(t32)) return 0;
	switch (t32.type) {
		case x.Array:
			return 1;
		case x.Boolean:
			return 2;
		case x.Color:
			return 3;
		case x.Date:
			return 4;
		case x.Enum:
			return 5;
		case x.File:
			return 6;
		case x.ResponsiveImage:
			return 10;
		case x.Link:
			return 7;
		case x.Number:
			return 8;
		case x.Object:
			return 9;
		case x.RichText:
			return 11;
		case x.String:
			return 12;
		case x.VectorSetItem:
			return 13;
		default:
			b(t32);
	}
}
function R(e42) {
	let r22 = e42.readUint16(),
		n22 = [];
	for (let i22 = 0; i22 < r22; i22++) {
		let r3 = t.read(e42);
		n22.push(r3);
	}
	return {
		type: x.Array,
		value: n22,
	};
}
function q(e42, r22) {
	for (let n22 of (e42.writeUint16(r22.value.length), r22.value))
		t.write(e42, n22);
}
function _(e42, r22, n22) {
	let i22 = e42.value.length,
		s2 = r22.value.length;
	if (i22 < s2) return -1;
	if (i22 > s2) return 1;
	for (let s3 = 0; s3 < i22; s3++) {
		let i3 = e42.value[s3],
			a2 = r22.value[s3],
			o22 = t.compare(i3, a2, n22);
		if (0 !== o22) return o22;
	}
	return 0;
}
function D(t32) {
	return {
		type: x.Boolean,
		value: 0 !== t32.readUint8(),
	};
}
function j(t32, e42) {
	t32.writeUint8(e42.value ? 1 : 0);
}
function C(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function J(t32) {
	return {
		type: x.Color,
		value: t32.readString(),
	};
}
function V(t32, e42) {
	t32.writeString(e42.value);
}
function W(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function $(t32) {
	let e42 = t32.readInt64(),
		r22 = new Date(e42);
	return {
		type: x.Date,
		value: r22.toISOString(),
	};
}
function z(t32, e42) {
	let r22 = new Date(e42.value),
		n22 = r22.getTime();
	t32.writeInt64(n22);
}
function G(t32, e42) {
	let r22 = new Date(t32.value),
		n22 = new Date(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function K(t32) {
	return {
		type: x.Enum,
		value: t32.readString(),
	};
}
function H(t32, e42) {
	t32.writeString(e42.value);
}
function X(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function Q(t32) {
	return {
		type: x.File,
		value: t32.readString(),
	};
}
function Y(t32, e42) {
	t32.writeString(e42.value);
}
function Z(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function tt(t32) {
	return {
		type: x.Link,
		value: t32.readJson(),
	};
}
function te(t32, e42) {
	t32.writeJson(e42.value);
}
function tr(t32, e42) {
	let r22 = JSON.stringify(t32.value),
		n22 = JSON.stringify(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function tn(t32) {
	return {
		type: x.Number,
		value: t32.readFloat64(),
	};
}
function ti(t32, e42) {
	t32.writeFloat64(e42.value);
}
function ts(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function ta(e42) {
	let r22 = e42.readUint16(),
		n22 = {};
	for (let i22 = 0; i22 < r22; i22++) {
		let r3 = e42.readString();
		n22[r3] = t.read(e42);
	}
	return {
		type: x.Object,
		value: n22,
	};
}
function to(e42, r22) {
	let n22 = Object.entries(r22.value);
	for (let [r3, i22] of (e42.writeUint16(n22.length), n22))
		e42.writeString(r3), t.write(e42, i22);
}
function tu(e42, r22, n22) {
	let i22 = Object.keys(e42.value).sort(),
		s2 = Object.keys(r22.value).sort();
	if (i22.length < s2.length) return -1;
	if (i22.length > s2.length) return 1;
	for (let a2 = 0; a2 < i22.length; a2++) {
		let o22 = i22[a2],
			u22 = s2[a2];
		if (o22 < u22) return -1;
		if (o22 > u22) return 1;
		let l22 = e42.value[o22] ?? null,
			h2 = r22.value[u22] ?? null,
			c2 = t.compare(l22, h2, n22);
		if (0 !== c2) return c2;
	}
	return 0;
}
function tl(t32) {
	return {
		type: x.ResponsiveImage,
		value: t32.readJson(),
	};
}
function th(t32, e42) {
	t32.writeJson(e42.value);
}
function tc(t32, e42) {
	let r22 = JSON.stringify(t32.value),
		n22 = JSON.stringify(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function tf(t32) {
	return {
		type: x.RichText,
		value: t32.readUint32(),
	};
}
function tg(t32, e42) {
	t32.writeUint32(e42.value);
}
function td(t32, e42) {
	let r22 = t32.value,
		n22 = e42.value;
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function ty(t32) {
	return {
		type: x.String,
		value: t32.readString(),
	};
}
function tp(t32, e42) {
	t32.writeString(e42.value);
}
function tv(t32, e42, r22) {
	let n22 = t32.value,
		i22 = e42.value;
	return (0 === r22.type &&
		((n22 = t32.value.toLowerCase()), (i22 = e42.value.toLowerCase())),
	n22 < i22)
		? -1
		: n22 > i22
			? 1
			: 0;
}
function tm(t32) {
	return {
		type: x.VectorSetItem,
		value: t32.readUint32(),
	};
}
function tw(t32, e42) {
	t32.writeUint32(e42.value);
}
function tI(t32, e42) {
	let r22 = t32.value,
		n22 = e42.value;
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
((t32) => {
	(t32.read = function (t42) {
		let e42 = t42.readUint8();
		switch (e42) {
			case 0:
				return null;
			case 1:
				return R(t42);
			case 2:
				return D(t42);
			case 3:
				return J(t42);
			case 4:
				return $(t42);
			case 5:
				return K(t42);
			case 6:
				return Q(t42);
			case 7:
				return tt(t42);
			case 8:
				return tn(t42);
			case 9:
				return ta(t42);
			case 10:
				return tl(t42);
			case 11:
				return tf(t42);
			case 12:
				return ty(t42);
			case 13:
				return tm(t42);
			default:
				b(e42);
		}
	}),
		(t32.write = function (t42, e42) {
			let r22 = P(e42);
			if ((t42.writeUint8(r22), !A(e42)))
				switch (e42.type) {
					case x.Array:
						return q(t42, e42);
					case x.Boolean:
						return j(t42, e42);
					case x.Color:
						return V(t42, e42);
					case x.Date:
						return z(t42, e42);
					case x.Enum:
						return H(t42, e42);
					case x.File:
						return Y(t42, e42);
					case x.Link:
						return te(t42, e42);
					case x.Number:
						return ti(t42, e42);
					case x.Object:
						return to(t42, e42);
					case x.ResponsiveImage:
						return th(t42, e42);
					case x.RichText:
						return tg(t42, e42);
					case x.VectorSetItem:
						return tw(t42, e42);
					case x.String:
						return tp(t42, e42);
					default:
						b(e42);
				}
		}),
		(t32.compare = function (t42, e42, r22) {
			let n22 = P(t42),
				i22 = P(e42);
			if (n22 < i22) return -1;
			if (n22 > i22) return 1;
			if (A(t42) || A(e42)) return 0;
			switch (t42.type) {
				case x.Array:
					return I(e42.type === x.Array), _(t42, e42, r22);
				case x.Boolean:
					return I(e42.type === x.Boolean), C(t42, e42);
				case x.Color:
					return I(e42.type === x.Color), W(t42, e42);
				case x.Date:
					return I(e42.type === x.Date), G(t42, e42);
				case x.Enum:
					return I(e42.type === x.Enum), X(t42, e42);
				case x.File:
					return I(e42.type === x.File), Z(t42, e42);
				case x.Link:
					return I(e42.type === x.Link), tr(t42, e42);
				case x.Number:
					return I(e42.type === x.Number), ts(t42, e42);
				case x.Object:
					return I(e42.type === x.Object), tu(t42, e42, r22);
				case x.ResponsiveImage:
					return I(e42.type === x.ResponsiveImage), tc(t42, e42);
				case x.RichText:
					return I(e42.type === x.RichText), td(t42, e42);
				case x.VectorSetItem:
					return I(e42.type === x.VectorSetItem), tI(t42, e42);
				case x.String:
					return I(e42.type === x.String), tv(t42, e42, r22);
				default:
					b(t42);
			}
		});
})(t || (t = {}));
var tU = 3;
var tS = 250;
var tk = [
	408,
	// Request Timeout
	429,
	// Too Many Requests
	500,
	// Internal Server Error
	502,
	// Bad Gateway
	503,
	// Service Unavailable
	504,
];
var tL = async (t32, e42) => {
	let r22 = 0;
	for (;;) {
		try {
			let n22 = await fetch(t32, e42);
			if (!tk.includes(n22.status) || ++r22 > tU) return n22;
		} catch (t42) {
			if (e42?.signal?.aborted || ++r22 > tU) throw t42;
		}
		await tB(r22);
	}
};
async function tB(t32) {
	let e42 = Math.floor(tS * (Math.random() + 1) * 2 ** (t32 - 1));
	await new Promise((t42) => {
		setTimeout(t42, e42);
	});
}
async function tE(t32, e42) {
	let r22 = tF(e42),
		n22 = [],
		i22 = 0;
	for (let t42 of r22)
		n22.push(`${t42.from}-${t42.to - 1}`), (i22 += t42.to - t42.from);
	let s2 = new URL(t32),
		a2 = n22.join(",");
	s2.searchParams.set("range", a2);
	let o22 = await tL(s2);
	if (200 !== o22.status)
		throw Error(`Request failed: ${o22.status} ${o22.statusText}`);
	let u22 = await o22.arrayBuffer(),
		l22 = new Uint8Array(u22);
	if (l22.length !== i22)
		throw Error("Request failed: Unexpected response length");
	let h2 = new tM(),
		c2 = 0;
	for (let t42 of r22) {
		let e5 = t42.to - t42.from,
			r3 = c2 + e5,
			n3 = l22.subarray(c2, r3);
		h2.write(t42.from, n3), (c2 = r3);
	}
	return e42.map((t42) => h2.read(t42.from, t42.to - t42.from));
}
var tM = class {
	read(t32, e42) {
		for (let r22 of this.chunks) {
			if (t32 < r22.start) break;
			if (t32 > r22.end) continue;
			if (t32 + e42 > r22.end) break;
			let n22 = t32 - r22.start,
				i22 = n22 + e42;
			return r22.data.slice(n22, i22);
		}
		throw Error("Missing data");
	}
	write(t32, e42) {
		let r22 = t32,
			n22 = r22 + e42.length,
			i22 = 0,
			s2 = this.chunks.length;
		for (; i22 < s2; i22++) {
			let t42 = this.chunks[i22];
			if ((I(t42, "Missing chunk"), !(r22 > t42.end))) {
				if (r22 > t42.start) {
					let n3 = r22 - t42.start,
						i3 = t42.data.subarray(0, n3);
					(e42 = tT(i3, e42)), (r22 = t42.start);
				}
				break;
			}
		}
		for (; s2 > i22; s2--) {
			let t42 = this.chunks[s2 - 1];
			if ((I(t42, "Missing chunk"), !(n22 < t42.start))) {
				if (n22 < t42.end) {
					let r3 = n22 - t42.start,
						i3 = t42.data.subarray(r3);
					(e42 = tT(e42, i3)), (n22 = t42.end);
				}
				break;
			}
		}
		let a2 = {
				start: r22,
				end: n22,
				data: e42,
			},
			o22 = s2 - i22;
		this.chunks.splice(i22, o22, a2);
	}
	constructor() {
		c(this, "chunks", []);
	}
};
function tT(t32, e42) {
	let r22 = t32.length + e42.length,
		n22 = new Uint8Array(r22);
	return n22.set(t32, 0), n22.set(e42, t32.length), n22;
}
function tF(t32) {
	I(t32.length > 0, "Must have at least one range");
	let e42 = [...t32].sort((t42, e5) => t42.from - e5.from),
		r22 = [];
	for (let t42 of e42) {
		let e5 = r22.length - 1,
			n22 = r22[e5];
		n22 && t42.from <= n22.to
			? (r22[e5] = {
					from: n22.from,
					to: Math.max(n22.to, t42.to),
				})
			: r22.push(t42);
	}
	return r22;
}
var tA = class e3 {
	static read(r22) {
		let n22 = new e3(),
			i22 = r22.readUint16();
		for (let e42 = 0; e42 < i22; e42++) {
			let e5 = r22.readString(),
				i3 = t.read(r22);
			n22.setField(e5, i3);
		}
		return n22;
	}
	write(e42) {
		for (let [r22, n22] of (e42.writeUint16(this.fields.size), this.fields))
			e42.writeString(r22), t.write(e42, n22);
	}
	getData() {
		let t32 = {};
		for (let [e42, r22] of this.fields) t32[e42] = r22;
		return t32;
	}
	setField(t32, e42) {
		this.fields.set(t32, e42);
	}
	getField(t32) {
		return this.fields.get(t32);
	}
	constructor() {
		c(this, "fields", /* @__PURE__ */ new Map());
	}
};
var tO = class {
	scanItems() {
		return (
			(this.itemsPromise ??= tL(this.url).then(async (t32) => {
				if (!t32.ok)
					throw Error(`Request failed: ${t32.status} ${t32.statusText}`);
				let e42 = await t32.arrayBuffer(),
					r22 = new Uint8Array(e42),
					n22 = new y(r22),
					i22 = [],
					s2 = n22.readUint32();
				for (let t42 = 0; t42 < s2; t42++) {
					let t5 = n22.getOffset(),
						e5 = tA.read(n22),
						r3 = n22.getOffset() - t5,
						s3 = new O(this.id, t5, r3),
						a2 = s3.toString(),
						o22 = {
							pointer: a2,
							data: e5.getData(),
						};
					this.itemLoader.prime(a2, o22), i22.push(o22);
				}
				return i22;
			})),
			this.itemsPromise
		);
	}
	resolveItem(t32) {
		return this.itemLoader.load(t32);
	}
	constructor(t32, e42) {
		(this.id = t32),
			(this.url = e42),
			c(this, "itemsPromise"),
			c(
				this,
				"itemLoader",
				new g.default(async (t42) => {
					let e5 = t42.map((t5) => {
							let e6 = O.fromString(t5);
							return {
								from: e6.offset,
								to: e6.offset + e6.length,
							};
						}),
						r22 = await tE(this.url, e5);
					return r22.map((e6, r3) => {
						let n22 = new y(e6),
							i22 = tA.read(n22),
							s2 = t42[r3];
						return (
							I(s2, "Missing pointer"),
							{
								pointer: s2,
								data: i22.getData(),
							}
						);
					});
				}),
			);
	}
};
var tx = class {
	async scanItems() {
		let t32 = await Promise.all(
			this.chunks.map(async (t42) => t42.scanItems()),
		);
		return t32.flat();
	}
	async resolveItems(t32) {
		return Promise.all(
			t32.map((t42) => {
				let e42 = O.fromString(t42),
					r22 = this.chunks[e42.chunkId];
				return I(r22, "Missing chunk"), r22.resolveItem(t42);
			}),
		);
	}
	compareItems(t32, e42) {
		let r22 = O.fromString(t32.pointer),
			n22 = O.fromString(e42.pointer);
		return r22.compare(n22);
	}
	compareValues(e42, r22, n22) {
		return t.compare(e42, r22, n22);
	}
	constructor(t32) {
		(this.options = t32),
			c(this, "schema"),
			c(this, "indexes"),
			c(this, "resolveRichText"),
			c(this, "resolveVectorSetItem"),
			c(this, "chunks"),
			(this.chunks = this.options.chunks.map((t42, e42) => new tO(e42, t42))),
			(this.schema = t32.schema),
			(this.indexes = t32.indexes),
			(this.resolveRichText = t32.resolveRichText),
			(this.resolveVectorSetItem = t32.resolveVectorSetItem);
	}
};

// /:https://framerusercontent.com/modules/g0Nz5LZJx3cYVkiD7uS1/JGIdW4ek1nGSKkTT9gya/FQ9Fz288R-1.js
var t3 = (t22, e22) => async () => {
	let r22 = await t22();
	return r22[e22];
};
var e2 = () => import("./chunks/FQ9Fz288R-2-NLPRLUQU.js");
var r2 = [
	t3(e2, "richText"),
	t3(e2, "richText1"),
	t3(e2, "richText2"),
	t3(e2, "richText3"),
	t3(e2, "richText4"),
	t3(e2, "richText5"),
	t3(e2, "richText6"),
	t3(e2, "richText7"),
	t3(e2, "richText8"),
	t3(e2, "richText9"),
	t3(e2, "richText10"),
	t3(e2, "richText11"),
	t3(e2, "richText12"),
	t3(e2, "richText13"),
	t3(e2, "richText14"),
	t3(e2, "richText15"),
	t3(e2, "richText16"),
	t3(e2, "richText17"),
	t3(e2, "richText18"),
	t3(e2, "richText19"),
	t3(e2, "richText20"),
	t3(e2, "richText21"),
	t3(e2, "richText22"),
	t3(e2, "richText23"),
];
async function resolveRichText(t22) {
	let e22 = r2[t22];
	if (e22) return await e22();
}

// /:https://framerusercontent.com/modules/g0Nz5LZJx3cYVkiD7uS1/JGIdW4ek1nGSKkTT9gya/FQ9Fz288R.js
var n2 = {
	E5Kf_kQMG: {
		isNullable: true,
		type: t4.RichText,
	},
	gM8_SX4ka: {
		isNullable: true,
		type: t4.String,
	},
	id: {
		isNullable: false,
		type: t4.String,
	},
	L2np3nwpe: {
		isNullable: true,
		type: t4.RichText,
	},
	ljOVMfd7C: {
		isNullable: true,
		type: t4.String,
	},
	nextItemId: {
		isNullable: true,
		type: t4.String,
	},
	previousItemId: {
		isNullable: true,
		type: t4.String,
	},
	SVUUOmaTq: {
		isNullable: true,
		type: t4.RichText,
	},
	tittXOToG: {
		isNullable: true,
		type: t4.String,
	},
	UbLNj3BJV: {
		isNullable: true,
		type: t4.String,
	},
	w12FzdhrB: {
		isNullable: true,
		type: t4.Boolean,
	},
	Y3ljWbYbb: {
		isNullable: true,
		type: t4.String,
	},
};
var o2 = [];
var u2 = (e22) => {
	let t22 = o2[e22];
	if (t22) return t22().then((e32) => e32.default);
};
var p2 = new i2();
var d2 = new l2(p2);
var y2 = {
	collectionByLocaleId: {
		default: new tx({
			chunks: [
				new URL(
					"./FQ9Fz288R-chunk-default-0.framercms",
					"https://framerusercontent.com/modules/g0Nz5LZJx3cYVkiD7uS1/JGIdW4ek1nGSKkTT9gya/FQ9Fz288R.js",
				).href.replace("/modules/", "/cms/"),
			],
			indexes: [],
			resolveRichText,
			resolveVectorSetItem: u2,
			schema: n2,
		}),
	},
	displayName: "Careers",
};
var stdin_default4 = y2;
e4(y2, {
	tittXOToG: {
		defaultValue: "",
		title: "Role",
		type: t4.String,
	},
	Y3ljWbYbb: {
		defaultValue: "",
		title: "Department",
		type: t4.String,
	},
	w12FzdhrB: {
		defaultValue: true,
		title: "Remote",
		type: t4.Boolean,
	},
	gM8_SX4ka: {
		defaultValue: "",
		title: "Location",
		type: t4.String,
	},
	UbLNj3BJV: {
		defaultValue: "",
		placeholder: "We're looking for...",
		title: "Description",
		type: t4.String,
	},
	SVUUOmaTq: {
		defaultValue: "",
		title: "What you'll do",
		type: t4.RichText,
	},
	E5Kf_kQMG: {
		defaultValue: "",
		title: "Who you are",
		type: t4.RichText,
	},
	L2np3nwpe: {
		defaultValue: "",
		title: "What we offer",
		type: t4.RichText,
	},
	ljOVMfd7C: {
		title: "Slug",
		type: t4.String,
	},
	previousItemId: {
		dataIdentifier: "local-module:collection/FQ9Fz288R:default",
		title: "Previous",
		type: t4.CollectionReference,
	},
	nextItemId: {
		dataIdentifier: "local-module:collection/FQ9Fz288R:default",
		title: "Next",
		type: t4.CollectionReference,
	},
});

// /:https://framerusercontent.com/modules/d1MpT40KioIDqsrEmbV7/sRL6Z5irHHN43U1n241V/lI3TAAqCg.js
import { fontStore } from "unframer";
fontStore.loadFonts(["GF;Geist Mono-500", "GF;Geist Mono-700"]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Geist Mono",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeEPKJ5W7ihaO_CS.woff2",
				weight: "500",
			},
			{
				family: "Geist Mono",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeHaL55W7ihaO_CS.woff2",
				weight: "700",
			},
		],
	},
];
var css5 = [
	'.framer-2R0Ln .framer-styles-preset-1klae7r:not(.rich-text-wrapper), .framer-2R0Ln .framer-styles-preset-1klae7r.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Geist Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: 0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }',
];
var className3 = "framer-2R0Ln";

// /:https://framerusercontent.com/modules/FVPdLQuH5FgmfojRjedc/zU9EhP4CHWDDE1h07lkm/nMVen8H4h.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;Geist Mono-500",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Geist Mono",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeEPKJ5W7ihaO_CS.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css6 = [
	'.framer-PSOq7 .framer-styles-preset-adl1m0:not(.rich-text-wrapper), .framer-PSOq7 .framer-styles-preset-adl1m0.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 9px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }',
];
var className4 = "framer-PSOq7";

// /:https://framerusercontent.com/modules/dQZOS00ARXstCRjr6iYz/g3K3Ulq70TtS0U9REaM0/xN9fPUCLr.js
var CMSItemCounterFonts = getFonts(CMSCounter);
var cycleOrder = ["By6YV2LCZ", "BhZiciee_", "uRGLXyHq_"];
var serializationHash = "framer-2FTbp";
var variantClassNames = {
	BhZiciee_: "framer-v-1hjye5k",
	By6YV2LCZ: "framer-v-xabskk",
	uRGLXyHq_: "framer-v-8vhxcj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var QueryData = ({ query: query2, pageSize, children }) => {
	const data = useQueryData2(query2);
	return children(data);
};
var negate = (value) => {
	return !value;
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion3.create(React3.Fragment);
var humanReadableVariantMap = {
	Default: "By6YV2LCZ",
	Hover: "BhZiciee_",
	Phone: "uRGLXyHq_",
};
var getProps3 = ({ height, id, jobsCount, label, width, ...props }) => {
	return {
		...props,
		szddn_HYc: jobsCount ?? props.szddn_HYc,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "By6YV2LCZ",
		xaZ_KKZMG: label ?? props.xaZ_KKZMG ?? "NEW",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		xaZ_KKZMG,
		szddn_HYc,
		ljOVMfd7CmxeRHLioC,
		tittXOToGmxeRHLioC,
		idmxeRHLioC,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "By6YV2LCZ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className4, className3];
	const scopingClassNames = cx3(serializationHash, ...sharedStyleClassNames);
	const visible = negate(szddn_HYc);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-xabskk",
							className5,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"By6YV2LCZ"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							borderBottomLeftRadius: 4,
							borderBottomRightRadius: 4,
							borderTopLeftRadius: 4,
							borderTopRightRadius: 4,
							...style,
						}}
						variants={{
							BhZiciee_: {
								backgroundColor:
									"var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))",
							},
							uRGLXyHq_: {
								backgroundColor: "rgba(0, 0, 0, 0)",
								borderBottomLeftRadius: 6,
								borderBottomRightRadius: 6,
								borderTopLeftRadius: 6,
								borderTopRightRadius: 6,
							},
						}}
						{...addPropertyOverrides(
							{
								BhZiciee_: {
									"data-framer-name": "Hover",
								},
								uRGLXyHq_: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-1m0zidl"}
							data-framer-name={"BG"}
							layoutDependency={layoutDependency}
							layoutId={"n6hhNro_s"}
							style={{
								backgroundColor:
									"var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))",
								opacity: 0.1,
							}}
						/>
						{szddn_HYc && (
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-f9g24e-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"D_Eo1DOLa-container"}
									nodeId={"D_Eo1DOLa"}
									rendersWithMotion={true}
									scopeId={"xN9fPUCLr"}
								>
									<CMSCounter
										collectionList={[
											<motion3.div
												className={"framer-1jn68f3"}
												data-framer-name={"Used For Counting Items"}
												layoutDependency={layoutDependency}
												layoutId={"mxeRHLioC"}
											>
												<ChildrenCanSuspend>
													<QueryData
														query={{
															from: {
																alias: "mxeRHLioC",
																data: stdin_default4,
																type: "Collection",
															},
															limit: {
																type: "LiteralValue",
																value: 10,
															},
															select: [
																{
																	collection: "mxeRHLioC",
																	name: "ljOVMfd7C",
																	type: "Identifier",
																},
																{
																	collection: "mxeRHLioC",
																	name: "tittXOToG",
																	type: "Identifier",
																},
																{
																	collection: "mxeRHLioC",
																	name: "id",
																	type: "Identifier",
																},
															],
														}}
													>
														{(collection, paginationInfo, loadMore) => (
															<_Fragment>
																{collection?.map(
																	(
																		{
																			id: idmxeRHLioC2,
																			ljOVMfd7C: ljOVMfd7CmxeRHLioC2,
																			tittXOToG: tittXOToGmxeRHLioC2,
																		},
																		index,
																	) => {
																		ljOVMfd7CmxeRHLioC2 ??= "";
																		tittXOToGmxeRHLioC2 ??= "";
																		return (
																			<LayoutGroup
																				id={`mxeRHLioC-${idmxeRHLioC2}`}
																			>
																				<PathVariablesContext.Provider
																					value={{
																						ljOVMfd7C: ljOVMfd7CmxeRHLioC2,
																					}}
																				>
																					<Link
																						href={{
																							pathVariables: {
																								ljOVMfd7C: ljOVMfd7CmxeRHLioC2,
																							},
																							webPageId: "Agq1L2jDe",
																						}}
																						motionChild={true}
																						nodeId={"LxTdgJsEt"}
																						scopeId={"xN9fPUCLr"}
																					>
																						<motion3.a
																							className={
																								"framer-1gdm1ey framer-10u6ba4"
																							}
																							layoutDependency={
																								layoutDependency
																							}
																							layoutId={"LxTdgJsEt"}
																						>
																							<RichText
																								__fromCanvasComponent={true}
																								className={"framer-17twrpx"}
																								data-framer-name={"Role"}
																								fonts={["Inter"]}
																								layoutDependency={
																									layoutDependency
																								}
																								layoutId={"xksCo6_j5"}
																								text={tittXOToGmxeRHLioC2}
																								verticalAlignment={"top"}
																								withExternalLayout={true}
																							>
																								<React3.Fragment>
																									<motion3.p
																										className={
																											"framer-styles-preset-2pjocb"
																										}
																										data-styles-preset={
																											"Dkr92TfXs"
																										}
																									>
																										{"Marketing Lead"}
																									</motion3.p>
																								</React3.Fragment>
																							</RichText>
																						</motion3.a>
																					</Link>
																				</PathVariablesContext.Provider>
																			</LayoutGroup>
																		);
																	},
																)}
															</_Fragment>
														)}
													</QueryData>
												</ChildrenCanSuspend>
											</motion3.div>,
										]}
										commas={false}
										font={{
											fontFamily: '"Geist Mono", monospace',
											fontSize: "9px",
											fontStyle: "normal",
											fontWeight: 500,
											letterSpacing: "0em",
											lineHeight: "1.6em",
										}}
										fontColor={
											"var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))"
										}
										height={"100%"}
										id={"D_Eo1DOLa"}
										layoutId={"D_Eo1DOLa"}
										placeholder={1}
										textSelect={true}
										width={"100%"}
										{...addPropertyOverrides(
											{
												BhZiciee_: {
													fontColor:
														"var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))",
												},
												uRGLXyHq_: {
													font: {
														fontFamily: '"Geist Mono", monospace',
														fontSize: "12px",
														fontStyle: "normal",
														fontWeight: 500,
														letterSpacing: "0em",
														lineHeight: "1.6em",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-gp326q"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"KJ0vou17m"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={xaZ_KKZMG}
								variants={{
									BhZiciee_: {
										"--extracted-r6o4lv":
											"var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										BhZiciee_: {
											children: (
												<React3.Fragment>
													<motion3.p
														className={"framer-styles-preset-adl1m0"}
														data-styles-preset={"nMVen8H4h"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0)))",
														}}
													>
														{"NEW"}
													</motion3.p>
												</React3.Fragment>
											),
										},
										uRGLXyHq_: {
											children: (
												<React3.Fragment>
													<motion3.p
														className={"framer-styles-preset-1klae7r"}
														data-styles-preset={"lI3TAAqCg"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)))",
														}}
													>
														{"NEW"}
													</motion3.p>
												</React3.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React3.Fragment>
									<motion3.p
										className={"framer-styles-preset-adl1m0"}
										data-styles-preset={"nMVen8H4h"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)))",
										}}
									>
										{"NEW"}
									</motion3.p>
								</React3.Fragment>
							</RichText>
						)}
						<motion3.div
							className={"framer-1yw2yda"}
							data-border={true}
							data-framer-name={"Border"}
							layoutDependency={layoutDependency}
							layoutId={"KqQXSqQpu"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 4,
								borderBottomRightRadius: 4,
								borderTopLeftRadius: 4,
								borderTopRightRadius: 4,
								opacity: 0.15,
							}}
							variants={{
								uRGLXyHq_: {
									borderBottomLeftRadius: 6,
									borderBottomRightRadius: 6,
									borderTopLeftRadius: 6,
									borderTopRightRadius: 6,
								},
							}}
						/>
					</motion3.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-2FTbp.framer-10u6ba4, .framer-2FTbp .framer-10u6ba4 { display: block; }",
	".framer-2FTbp.framer-xabskk { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 16px; justify-content: center; min-width: 16px; overflow: hidden; padding: 1px 5px 1px 5px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-2FTbp .framer-1m0zidl { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-2FTbp .framer-f9g24e-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-2FTbp .framer-1jn68f3 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; padding: 0px; position: relative; width: min-content; }",
	".framer-2FTbp .framer-1gdm1ey { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-2FTbp .framer-17twrpx, .framer-2FTbp .framer-gp326q { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-2FTbp .framer-1yw2yda { -webkit-user-select: none; bottom: 0px; flex: none; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-2FTbp.framer-v-8vhxcj.framer-xabskk { height: 24px; min-width: 24px; padding: 1px 6px 1px 6px; }",
	...css2,
	...css6,
	...css5,
	'.framer-2FTbp[data-border="true"]::after, .framer-2FTbp [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerxN9fPUCLr = withCSS3(Component3, css7, "framer-2FTbp");
var stdin_default5 = FramerxN9fPUCLr;
FramerxN9fPUCLr.displayName = "Nav Link Tag";
FramerxN9fPUCLr.defaultProps = {
	height: 16,
	width: 27,
};
addPropertyControls4(FramerxN9fPUCLr, {
	variant: {
		options: ["By6YV2LCZ", "BhZiciee_", "uRGLXyHq_"],
		optionTitles: ["Default", "Hover", "Phone"],
		title: "Variant",
		type: ControlType4.Enum,
	},
	xaZ_KKZMG: {
		defaultValue: "NEW",
		displayTextArea: false,
		title: "Label",
		type: ControlType4.String,
	},
	szddn_HYc: {
		defaultValue: false,
		description:
			'Set to "yes" if you want to show the number of available jobs. (Used on the Careers link)',
		title: "Jobs Count",
		type: ControlType4.Boolean,
	},
});
addFonts(
	FramerxN9fPUCLr,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Geist Mono",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/geistmono/v3/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeEPKJ5W7ihaO_CS.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...CMSItemCounterFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/OHflKOCQMR1MjQ2QbAzK/dTJqOZDABftP2chcf55F/YyGh9D7uE.js
var IconFonts = getFonts2(stdin_default3);
var TelegramLogoFonts = getFonts2(stdin_default2);
var NavLinkTagFonts = getFonts2(stdin_default5);
var MainSiteGridBorderFonts = getFonts2(stdin_default);
var cycleOrder2 = ["tZM8deVlt", "y5eGoIClO", "xwvpR2yRG", "DFvGbb_ip"];
var serializationHash2 = "framer-5IMhk";
var variantClassNames2 = {
	DFvGbb_ip: "framer-v-1jzpt4t",
	tZM8deVlt: "framer-v-41vbxj",
	xwvpR2yRG: "framer-v-d86dch",
	y5eGoIClO: "framer-v-j4r4nx",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion4.create(React4.Fragment);
var humanReadableVariantMap2 = {
	connected: "tZM8deVlt",
	farcaster: "DFvGbb_ip",
	telegram: "xwvpR2yRG",
	twitter: "y5eGoIClO",
};
var getProps4 = ({ height, id, twitterHandle, width, ...props }) => {
	return {
		...props,
		dA6d4Ndm7: twitterHandle ?? props.dA6d4Ndm7 ?? "@etogigi",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "tZM8deVlt",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		dA6d4Ndm7,
		...restProps
	} = getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "tZM8deVlt",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx4(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["xwvpR2yRG", "DFvGbb_ip"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "DFvGbb_ip") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "xwvpR2yRG") return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (["y5eGoIClO", "xwvpR2yRG", "DFvGbb_ip"].includes(baseVariant))
			return false;
		return true;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion4.div
						{...restProps}
						{...gestureHandlers}
						className={cx4(
							scopingClassNames,
							"framer-41vbxj",
							className5,
							classNames,
						)}
						data-framer-name={"connected"}
						layoutDependency={layoutDependency}
						layoutId={"tZM8deVlt"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								DFvGbb_ip: {
									"data-framer-name": "farcaster",
								},
								xwvpR2yRG: {
									"data-framer-name": "telegram",
								},
								y5eGoIClO: {
									"data-framer-name": "twitter",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion4.div
							className={"framer-17nsqyv"}
							data-framer-name={"Icon Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"LMjoMfaWZ"}
							style={{
								backgroundColor:
									"var(--token-ab91763a-bd8d-4b8f-92c1-f89e2462855c, rgb(28, 28, 28))",
								borderBottomLeftRadius: 188,
								borderBottomRightRadius: 188,
								borderTopLeftRadius: 188,
								borderTopRightRadius: 188,
							}}
						>
							{isDisplayed() &&
								_jsx4(stdin_default3, {
									animated: true,
									className: "framer-1edru9s",
									layoutDependency,
									layoutId: "ke3gdGvzn",
									style: {
										"--1ya7007": "rgb(255, 255, 255)",
									},
								})}
							{isDisplayed1() && (
								<SVG3
									className={"framer-1eoy5bc"}
									layoutDependency={layoutDependency}
									layoutId={"aVuPf1ZRj"}
									opacity={1}
									requiresOverflowVisible={false}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 23.52" overflow="visible"></svg>'
									}
									withExternalLayout={true}
									{...addPropertyOverrides2(
										{
											DFvGbb_ip: {
												svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 23.52" overflow="visible"><path d="M 18.24 0 L 5.76 0 C 2.579 0 0 2.579 0 5.76 L 0 17.76 C 0 20.941 2.579 23.52 5.76 23.52 L 18.24 23.52 C 21.421 23.52 24 20.941 24 17.76 L 24 5.76 C 24 2.579 21.421 0 18.24 0 M 19.056 17.166 L 19.056 17.67 C 19.193 17.655 19.33 17.699 19.434 17.79 C 19.537 17.881 19.597 18.012 19.599 18.15 L 19.599 18.718 L 14.456 18.718 L 14.456 18.149 C 14.458 18.011 14.519 17.88 14.622 17.789 C 14.726 17.698 14.863 17.655 15 17.67 L 15 17.166 C 15 16.946 15.152 16.764 15.358 16.708 L 15.348 12.344 C 15.19 10.607 13.708 9.246 11.905 9.246 C 10.101 9.246 8.62 10.607 8.462 12.344 L 8.452 16.702 C 8.68 16.744 8.984 16.91 8.992 17.166 L 8.992 17.67 C 9.129 17.655 9.266 17.699 9.37 17.79 C 9.473 17.881 9.533 18.012 9.535 18.15 L 9.535 18.718 L 4.391 18.718 L 4.391 18.149 C 4.393 18.011 4.454 17.88 4.557 17.789 C 4.661 17.698 4.798 17.655 4.935 17.67 L 4.935 17.166 C 4.935 16.913 5.136 16.712 5.389 16.694 L 5.389 8.799 L 4.899 8.799 L 4.289 6.768 L 6.93 6.768 L 6.93 4.802 L 16.88 4.802 L 16.88 6.768 L 19.702 6.768 L 19.092 8.798 L 18.602 8.798 L 18.602 16.694 C 18.854 16.711 19.055 16.914 19.055 17.166" fill="rgb(255, 255, 255)"></path></svg>',
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SVG3
										className={"framer-1jolf6w"}
										layoutDependency={layoutDependency}
										layoutId={"sw8d665GJ"}
										opacity={1}
										requiresOverflowVisible={false}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 23.52" overflow="visible"><path d="M 18.24 0 L 5.76 0 C 2.579 0 0 2.579 0 5.76 L 0 17.76 C 0 20.941 2.579 23.52 5.76 23.52 L 18.24 23.52 C 21.421 23.52 24 20.941 24 17.76 L 24 5.76 C 24 2.579 21.421 0 18.24 0" fill="transparent"></path></svg>'
										}
										withExternalLayout={true}
									/>
									<SVG3
										className={"framer-1x5l9fg"}
										layoutDependency={layoutDependency}
										layoutId={"U59ZpVjzI"}
										opacity={1}
										requiresOverflowVisible={false}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 15.413 13.916" overflow="visible"><path d="M 14.767 12.364 L 14.767 12.868 C 14.904 12.853 15.041 12.897 15.145 12.988 C 15.248 13.079 15.308 13.21 15.31 13.348 L 15.31 13.916 L 10.167 13.916 L 10.167 13.347 C 10.169 13.209 10.23 13.078 10.333 12.987 C 10.437 12.896 10.574 12.853 10.711 12.868 L 10.711 12.364 C 10.711 12.144 10.863 11.962 11.069 11.906 L 11.059 7.542 C 10.901 5.805 9.419 4.444 7.616 4.444 C 5.812 4.444 4.331 5.805 4.173 7.542 L 4.163 11.9 C 4.391 11.942 4.695 12.108 4.703 12.364 L 4.703 12.868 C 4.84 12.853 4.977 12.897 5.081 12.988 C 5.184 13.079 5.244 13.21 5.246 13.348 L 5.246 13.916 L 0.102 13.916 L 0.102 13.347 C 0.104 13.209 0.165 13.078 0.268 12.987 C 0.372 12.896 0.509 12.853 0.646 12.868 L 0.646 12.364 C 0.646 12.111 0.847 11.91 1.1 11.892 L 1.1 3.997 L 0.61 3.997 L 0 1.966 L 2.641 1.966 L 2.641 0 L 12.591 0 L 12.591 1.966 L 15.413 1.966 L 14.803 3.996 L 14.313 3.996 L 14.313 11.892 C 14.565 11.909 14.766 12.112 14.766 12.364" fill="transparent"></path></svg>'
										}
										withExternalLayout={true}
									/>
								</SVG3>
							)}
							{isDisplayed2() &&
								_jsx4(stdin_default2, {
									animated: true,
									className: "framer-128miir",
									layoutDependency,
									layoutId: "hsriskTCY",
									style: {
										"--1m6trwb": 0,
										"--21h8s6":
											"var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))",
										"--pgex8v": 1.75,
									},
								})}
						</motion4.div>
						<motion4.div
							className={"framer-tae232"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"Ml4Aj8sCH"}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-12ad7jd"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"SHcgECTxi"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={dA6d4Ndm7}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides2(
									{
										DFvGbb_ip: {
											children: (
												<React4.Fragment>
													<motion4.p
														className={"framer-styles-preset-ujo3da"}
														data-styles-preset={"sQrIs9_t0"}
														style={{
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))",
														}}
													>
														<motion4.code>
															{"Connect your Farcaster account"}
														</motion4.code>
													</motion4.p>
												</React4.Fragment>
											),
										},
										xwvpR2yRG: {
											children: (
												<React4.Fragment>
													<motion4.p
														className={"framer-styles-preset-ujo3da"}
														data-styles-preset={"sQrIs9_t0"}
														style={{
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))",
														}}
													>
														<motion4.code>
															{"Connect your Telegram account"}
														</motion4.code>
													</motion4.p>
												</React4.Fragment>
											),
										},
										y5eGoIClO: {
											children: (
												<React4.Fragment>
													<motion4.p
														className={"framer-styles-preset-ujo3da"}
														data-styles-preset={"sQrIs9_t0"}
														style={{
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))",
														}}
													>
														<motion4.code>
															{"Connect your X/Twitter account"}
														</motion4.code>
													</motion4.p>
												</React4.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React4.Fragment>
									<motion4.p
										className={"framer-styles-preset-ujo3da"}
										data-styles-preset={"sQrIs9_t0"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))",
										}}
									>
										<motion4.code>{"@etogigi"}</motion4.code>
									</motion4.p>
								</React4.Fragment>
							</RichText2>
						</motion4.div>
						{isDisplayed3() && (
							<ComponentViewportProvider2
								height={16}
								y={
									(componentViewport?.y || 0) +
									(24 + ((componentViewport?.height || 92) - 48 - 16) / 2)
								}
							>
								<SmartComponentScopedContainer2
									className={"framer-d1izv2-container"}
									layoutDependency={layoutDependency}
									layoutId={"iM1SBQIoH-container"}
									nodeId={"iM1SBQIoH"}
									rendersWithMotion={true}
									scopeId={"YyGh9D7uE"}
								>
									{_jsx4(stdin_default5, {
										height: "100%",
										id: "iM1SBQIoH",
										layoutId: "iM1SBQIoH",
										style: {
											height: "100%",
										},
										szddn_HYc: false,
										variant: "uRGLXyHq_",
										width: "100%",
										xaZ_KKZMG: "CONNECTED",
									})}
								</SmartComponentScopedContainer2>
							</ComponentViewportProvider2>
						)}
						<ComponentViewportProvider2
							height={(componentViewport?.height || 92) * 1}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								((componentViewport?.height || 92) * 0.5045045045045047 -
									((componentViewport?.height || 92) * 1) / 2)
							}
							{...addPropertyOverrides2(
								{
									DFvGbb_ip: {
										height: (componentViewport?.height || 91.5) * 1,
										y:
											(componentViewport?.y || 0) +
											((componentViewport?.height || 91.5) *
												0.5045045045045047 -
												((componentViewport?.height || 91.5) * 1) / 2),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer2
								className={"framer-n58odu-container"}
								layoutDependency={layoutDependency}
								layoutId={"ChmlWi3nf-container"}
								nodeId={"ChmlWi3nf"}
								rendersWithMotion={true}
								scopeId={"YyGh9D7uE"}
							>
								{_jsx4(stdin_default, {
									height: "100%",
									id: "ChmlWi3nf",
									layoutId: "ChmlWi3nf",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "CLljGfTtP",
									width: "100%",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
					</motion4.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css8 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5IMhk.framer-1o7jc16, .framer-5IMhk .framer-1o7jc16 { display: block; }",
	".framer-5IMhk.framer-41vbxj { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px 16px 24px 16px; position: relative; width: 358px; }",
	".framer-5IMhk .framer-17nsqyv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 10px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-5IMhk .framer-1edru9s, .framer-5IMhk .framer-128miir { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-5IMhk .framer-1eoy5bc { height: 24px; position: relative; width: 24px; }",
	".framer-5IMhk .framer-1jolf6w { height: 24px; left: 0px; position: absolute; top: 0px; width: 24px; }",
	".framer-5IMhk .framer-1x5l9fg { height: 14px; left: 5px; position: absolute; top: 5px; width: 16px; }",
	".framer-5IMhk .framer-tae232 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; z-index: 4; }",
	".framer-5IMhk .framer-12ad7jd { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-5IMhk .framer-d1izv2-container { flex: none; height: 16px; position: relative; width: auto; }",
	".framer-5IMhk .framer-n58odu-container { -webkit-user-select: none; flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); pointer-events: none; position: absolute; top: calc(50.45045045045047% - 100% / 2); user-select: none; width: 100%; z-index: 2; }",
	...css,
];
var FramerYyGh9D7uE = withCSS4(Component4, css8, "framer-5IMhk");
var stdin_default6 = FramerYyGh9D7uE;
FramerYyGh9D7uE.displayName = "SocialAccountItem";
FramerYyGh9D7uE.defaultProps = {
	height: 92,
	width: 358,
};
addPropertyControls5(FramerYyGh9D7uE, {
	variant: {
		options: ["tZM8deVlt", "y5eGoIClO", "xwvpR2yRG", "DFvGbb_ip"],
		optionTitles: ["connected", "twitter", "telegram", "farcaster"],
		title: "Variant",
		type: ControlType5.Enum,
	},
	dA6d4Ndm7: {
		defaultValue: "@etogigi",
		displayTextArea: false,
		title: "twitterHandle",
		type: ControlType5.String,
	},
});
addFonts2(
	FramerYyGh9D7uE,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...IconFonts,
		...TelegramLogoFonts,
		...NavLinkTagFonts,
		...MainSiteGridBorderFonts,
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:social-account-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SocialAccountItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var social_account_item_default = ComponentWithRoot;
export { social_account_item_default as default };
