// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c32b11589f2bc68b "humanpass", do not edit manually */
"use client";
import { useMainStore } from "../../src/store";
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Wallet' | 'Social' // Variant
 * walletText?: string // walletText
 * socialText?: string // socialText
}} Props

 */
var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, {
      get: all[name],
      enumerable: true,
    });
};

// virtual:connection-filter
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/E6pMSS8bXVGPehZHnQ0c/YUWpZyAtqvKVVvBvkkET/WM8ej8Dha.js
import * as React2 from "react";
import { useRef as useRef2 } from "react";
import {
  addFonts as addFonts2,
  addPropertyControls as addPropertyControls2,
  ComponentViewportProvider,
  ControlType as ControlType2,
  cx as cx2,
  getFonts,
  LayoutGroup as LayoutGroup2,
  motion as motion2,
  MotionConfigContext as MotionConfigContext2,
  SmartComponentScopedContainer,
  useComponentViewport as useComponentViewport2,
  useLocaleInfo as useLocaleInfo2,
  useVariantState as useVariantState2,
  withCodeBoundaryForOverrides,
  withCSS as withCSS2,
  withMappedReactProps,
} from "unframer";

// /:https://framerusercontent.com/modules/wJLp4ocFGeduHbUL36u9/FjOMmkYCITfXcYfFe7PM/HumanPass.js
import { forwardRef } from "react";

// /:https://framer.com/m/framer/store.js@^1.0.0
import * as React from "react";
import { useEffect, useRef, useState } from "react";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Data,
  getFontsFromSharedStyle,
  LayoutGroup,
  motion,
  MotionConfigContext,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useObserveData,
  useVariantState,
  withCSS,
} from "unframer";
function createStore(state1) {
  const dataStore = Data({
    state: Object.freeze({
      ...state1,
    }),
  });
  const setDataStore = (newState) => {
    if (typeof newState === "function") {
      newState = newState(dataStore.state);
    }
    dataStore.state = Object.freeze({
      ...dataStore.state,
      ...newState,
    });
  };
  let storeState =
    typeof state1 === "object"
      ? Object.freeze({
          ...state1,
        })
      : state1;
  const storeSetters = /* @__PURE__ */ new Set();
  const setStoreState = (newState) => {
    if (typeof newState === "function") {
      newState = newState(storeState);
    }
    storeState =
      typeof newState === "object"
        ? Object.freeze({
            ...storeState,
            ...newState,
          })
        : newState;
    storeSetters.forEach((setter) => setter(storeState));
  };
  function useStore2() {
    const [state, setState] = useState(storeState);
    useEffect(() => {
      storeSetters.add(setState);
      return () => storeSetters.delete(setState);
    }, []);
    if (useObserveData() === true) {
      useObserveData();
      return [dataStore.state, setDataStore];
    } else {
      return [state, setStoreState];
    }
  }
  return useStore2;
}

// /:https://framerusercontent.com/modules/wJLp4ocFGeduHbUL36u9/FjOMmkYCITfXcYfFe7PM/HumanPass.js
var useStore = createStore({
  background: "#0099FF",
});
function withOnClickWallets(Component3) {
  return /* @__PURE__ */ forwardRef((props, ref) => {
    const mainStore = useMainStore();
    return (
      <Component3
        ref={ref}
        {...props}
        onClick={() => mainStore.setSelectedFilter("Wallet")}
      />
    );
  });
}

function withOnClickSocialAccounts(Component3) {
  return /* @__PURE__ */ forwardRef((props, ref) => {
    const mainStore = useMainStore();
    return (
      <Component3
        ref={ref}
        {...props}
        onClick={() => mainStore.setSelectedFilter("Social")}
      />
    );
  });
}

// /:https://framerusercontent.com/modules/sFxxIBjOVZDQLMshOF2m/FZ1QAzm7K60eq9hG6ioJ/P8Lk6dtd8.js
var P8Lk6dtd8_exports = {};
__export(P8Lk6dtd8_exports, {
  __FramerMetadata__: () => __FramerMetadata__,
  default: () => stdin_default,
});

// /:https://framerusercontent.com/modules/kCW4L46BoEgCDDB7Rrgx/z7UxqxgDp1vl0DoSXrHY/Dkr92TfXs.js
import { fontStore } from "unframer";
fontStore.loadFonts([
  "BI;Raveo Variable/variable/v0",
  "BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTAw",
  "BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTAw",
  "BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTAw",
]);
var variationAxes = [
  {
    defaultValue: 14,
    maxValue: 32,
    minValue: 14,
    name: "Optical size",
    tag: "opsz",
  },
  {
    defaultValue: 400,
    maxValue: 900,
    minValue: 100,
    name: "Weight",
    tag: "wght",
  },
];
var fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Raveo Variable",
        source: "builtIn",
        style: "normal",
        url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
        variationAxes,
        weight: "1000",
      },
    ],
  },
];
var css = [
  '.framer-gN37g .framer-styles-preset-2pjocb:not(.rich-text-wrapper), .framer-gN37g .framer-styles-preset-2pjocb.rich-text-wrapper p { --framer-font-family: "Raveo Variable Variable", sans-serif; --framer-font-family-bold: "Raveo Variable Variable", sans-serif; --framer-font-family-bold-italic: "Raveo Variable Variable", sans-serif; --framer-font-family-italic: "Raveo Variable Variable", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: normal; --framer-font-style-italic: normal; --framer-font-variation-axes: "opsz" 14, "wght" 500; --framer-font-variation-axes-bold: "opsz" 14, "wght" 500; --framer-font-variation-axes-bold-italic: "opsz" 14, "wght" 500; --framer-font-variation-axes-italic: "opsz" 14, "wght" 500; --framer-font-weight: 1000; --framer-font-weight-bold: 1000; --framer-font-weight-bold-italic: 1000; --framer-font-weight-italic: 1000; --framer-letter-spacing: 0em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className = "framer-gN37g";

// /:https://framerusercontent.com/modules/e6BZtk7wcSCKPRWZNpAZ/XDyiNjdouIL9FRDGPH6E/Opptx2HbL.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
  "BI;Raveo Variable/variable/v0",
  "BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTAw",
  "BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTAw",
  "BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTAw",
]);
var variationAxes2 = [
  {
    defaultValue: 14,
    maxValue: 32,
    minValue: 14,
    name: "Optical size",
    tag: "opsz",
  },
  {
    defaultValue: 400,
    maxValue: 900,
    minValue: 100,
    name: "Weight",
    tag: "wght",
  },
];
var fonts2 = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Raveo Variable",
        source: "builtIn",
        style: "normal",
        url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
        variationAxes: variationAxes2,
        weight: "1000",
      },
    ],
  },
];
var css2 = [
  `.framer-MEpQ7 .framer-styles-preset-1inicq7:not(.rich-text-wrapper), .framer-MEpQ7 .framer-styles-preset-1inicq7.rich-text-wrapper p { --framer-font-family: "Raveo Variable Variable", sans-serif; --framer-font-family-bold: "Raveo Variable Variable", sans-serif; --framer-font-family-bold-italic: "Raveo Variable Variable", sans-serif; --framer-font-family-italic: "Raveo Variable Variable", sans-serif; --framer-font-open-type-features: 'tnum' on; --framer-font-size: 9px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: normal; --framer-font-style-italic: normal; --framer-font-variation-axes: "opsz" 14, "wght" 500; --framer-font-variation-axes-bold: "opsz" 14, "wght" 500; --framer-font-variation-axes-bold-italic: "opsz" 14, "wght" 500; --framer-font-variation-axes-italic: "opsz" 14, "wght" 500; --framer-font-weight: 1000; --framer-font-weight-bold: 1000; --framer-font-weight-bold-italic: 1000; --framer-font-weight-italic: 1000; --framer-letter-spacing: 0em; --framer-line-height: 1.7em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className2 = "framer-MEpQ7";

// /:https://framerusercontent.com/modules/IS0LtQ70F7CZLall12Kp/pavfa1B7e28Zdwywyj1W/sQrIs9_t0.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts([
  "BI;Raveo Variable/variable/v0",
  "BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
  "BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
  "BI;Raveo Variable/variable/v0VF=Im9wc3oiIDE0LCAid2dodCIgNTUw",
]);
var variationAxes3 = [
  {
    defaultValue: 14,
    maxValue: 32,
    minValue: 14,
    name: "Optical size",
    tag: "opsz",
  },
  {
    defaultValue: 400,
    maxValue: 900,
    minValue: 100,
    name: "Weight",
    tag: "wght",
  },
];
var fonts3 = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Raveo Variable",
        source: "builtIn",
        style: "normal",
        url: "https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2",
        variationAxes: variationAxes3,
        weight: "1000",
      },
    ],
  },
];
var css3 = [
  '.framer-D0GFO .framer-styles-preset-ujo3da:not(.rich-text-wrapper), .framer-D0GFO .framer-styles-preset-ujo3da.rich-text-wrapper p { --framer-font-family: "Raveo Variable Variable", sans-serif; --framer-font-family-bold: "Raveo Variable Variable", sans-serif; --framer-font-family-bold-italic: "Raveo Variable Variable", sans-serif; --framer-font-family-italic: "Raveo Variable Variable", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: normal; --framer-font-style-italic: normal; --framer-font-variation-axes: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold: "opsz" 14, "wght" 550; --framer-font-variation-axes-bold-italic: "opsz" 14, "wght" 550; --framer-font-variation-axes-italic: "opsz" 14, "wght" 550; --framer-font-weight: 1000; --framer-font-weight-bold: 1000; --framer-font-weight-bold-italic: 1000; --framer-font-weight-italic: 1000; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className3 = "framer-D0GFO";

// /:https://framerusercontent.com/modules/sFxxIBjOVZDQLMshOF2m/FZ1QAzm7K60eq9hG6ioJ/P8Lk6dtd8.js
var cycleOrder = ["PkLBxMzqm", "cDuHwnFRn", "s_vZxnWn9"];
var serializationHash = "framer-CX5qa";
var variantClassNames = {
  cDuHwnFRn: "framer-v-omf6cd",
  PkLBxMzqm: "framer-v-1fiyx4j",
  s_vZxnWn9: "framer-v-z867jq",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
var transition1 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: "spring",
};
var negate = (value) => {
  return !value;
};
var convertFromBoolean = (value, activeLocale) => {
  if (value) {
    return 'var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)) /* {"name":"Accent"} */';
  } else {
    return 'var(--token-fa07d228-afbe-4fad-9a44-2fb0dadd2a5e, rgb(23, 23, 23)) /* {"name":"Grey 03"} */';
  }
};
var toString = (value) => {
  return typeof value === "string" ? value : String(value);
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  );
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
  "Extra Small": "s_vZxnWn9",
  Medium: "cDuHwnFRn",
  Small: "PkLBxMzqm",
};
var getProps = ({ height, highlighted, id, title, width, ...props }) => {
  return {
    ...props,
    NjOVpa_TO: highlighted ?? props.NjOVpa_TO ?? true,
    qVFnPYB39: title ?? props.qVFnPYB39 ?? "Most popular",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "PkLBxMzqm",
  };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className: className4,
    layoutId,
    variant,
    qVFnPYB39,
    NjOVpa_TO,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "PkLBxMzqm",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [className, className3, className2];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const visible = negate(NjOVpa_TO);
  const fillColor = toString(convertFromBoolean(NjOVpa_TO, activeLocale));
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.div
            {...restProps}
            {...gestureHandlers}
            className={cx(
              scopingClassNames,
              "framer-1fiyx4j",
              className4,
              classNames
            )}
            data-framer-name={"Small"}
            layoutDependency={layoutDependency}
            layoutId={"PkLBxMzqm"}
            ref={refBinding}
            style={{
              borderBottomLeftRadius: 6,
              borderBottomRightRadius: 6,
              borderTopLeftRadius: 6,
              borderTopRightRadius: 6,
              ...style,
            }}
            variants={{
              cDuHwnFRn: {
                borderBottomLeftRadius: 8,
                borderBottomRightRadius: 8,
                borderTopLeftRadius: 8,
                borderTopRightRadius: 8,
              },
              s_vZxnWn9: {
                borderBottomLeftRadius: 4,
                borderBottomRightRadius: 4,
                borderTopLeftRadius: 4,
                borderTopRightRadius: 4,
              },
            }}
            {...addPropertyOverrides(
              {
                cDuHwnFRn: {
                  "data-framer-name": "Medium",
                },
                s_vZxnWn9: {
                  "data-framer-name": "Extra Small",
                },
              },
              baseVariant,
              gestureVariant
            )}
          >
            {NjOVpa_TO && (
              <RichText
                __fromCanvasComponent={true}
                className={"framer-ob4wjj"}
                data-framer-name={"Black"}
                fonts={["Inter"]}
                layoutDependency={layoutDependency}
                layoutId={"vbRxhRNmq"}
                style={{
                  "--extracted-r6o4lv":
                    "var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))",
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                }}
                text={qVFnPYB39}
                verticalAlignment={"top"}
                withExternalLayout={true}
                {...addPropertyOverrides(
                  {
                    cDuHwnFRn: {
                      children: (
                        <React.Fragment>
                          <motion.p
                            className={"framer-styles-preset-ujo3da"}
                            data-styles-preset={"sQrIs9_t0"}
                            style={{
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0)))",
                            }}
                          >
                            {"Most popular"}
                          </motion.p>
                        </React.Fragment>
                      ),
                    },
                    s_vZxnWn9: {
                      children: (
                        <React.Fragment>
                          <motion.p
                            className={"framer-styles-preset-1inicq7"}
                            data-styles-preset={"Opptx2HbL"}
                            style={{
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0)))",
                            }}
                          >
                            {"Most popular"}
                          </motion.p>
                        </React.Fragment>
                      ),
                    },
                  },
                  baseVariant,
                  gestureVariant
                )}
              >
                <React.Fragment>
                  <motion.p
                    className={"framer-styles-preset-2pjocb"}
                    data-styles-preset={"Dkr92TfXs"}
                    style={{
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0)))",
                    }}
                  >
                    {"Most popular"}
                  </motion.p>
                </React.Fragment>
              </RichText>
            )}
            {visible && (
              <RichText
                __fromCanvasComponent={true}
                className={"framer-1ywf30z"}
                data-framer-name={"White"}
                fonts={["Inter"]}
                layoutDependency={layoutDependency}
                layoutId={"AuBIWabpJ"}
                style={{
                  "--extracted-r6o4lv":
                    "var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))",
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                }}
                text={qVFnPYB39}
                verticalAlignment={"top"}
                withExternalLayout={true}
                {...addPropertyOverrides(
                  {
                    cDuHwnFRn: {
                      children: (
                        <React.Fragment>
                          <motion.p
                            className={"framer-styles-preset-ujo3da"}
                            data-styles-preset={"sQrIs9_t0"}
                            style={{
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))",
                            }}
                          >
                            {"Most popular"}
                          </motion.p>
                        </React.Fragment>
                      ),
                    },
                  },
                  baseVariant,
                  gestureVariant
                )}
              >
                <React.Fragment>
                  <motion.p
                    className={"framer-styles-preset-2pjocb"}
                    data-styles-preset={"Dkr92TfXs"}
                    style={{
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))",
                    }}
                  >
                    {"Most popular"}
                  </motion.p>
                </React.Fragment>
              </RichText>
            )}
            <motion.div
              className={"framer-jjg04g"}
              data-framer-name={"BG"}
              layoutDependency={layoutDependency}
              layoutId={"yH9foBo5Y"}
              style={{
                backgroundColor: fillColor,
              }}
            />
          </motion.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  );
});
var css4 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-CX5qa.framer-1np9pag, .framer-CX5qa .framer-1np9pag { display: block; }",
  ".framer-CX5qa.framer-1fiyx4j { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: hidden; padding: 0px 6px 0px 6px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-CX5qa .framer-ob4wjj, .framer-CX5qa .framer-1ywf30z { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; z-index: 3; }",
  ".framer-CX5qa .framer-jjg04g { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 1; }",
  ".framer-CX5qa.framer-v-omf6cd.framer-1fiyx4j { height: 28px; padding: 0px 8px 0px 8px; }",
  ".framer-CX5qa.framer-v-z867jq.framer-1fiyx4j { height: 20px; padding: 0px 5px 0px 5px; }",
  ...css,
  ...css3,
  ...css2,
];
var FramerP8Lk6dtd8 = withCSS(Component, css4, "framer-CX5qa");
var stdin_default = FramerP8Lk6dtd8;
FramerP8Lk6dtd8.displayName = "Tag";
FramerP8Lk6dtd8.defaultProps = {
  height: 24,
  width: 88,
};
addPropertyControls(FramerP8Lk6dtd8, {
  variant: {
    options: ["PkLBxMzqm", "cDuHwnFRn", "s_vZxnWn9"],
    optionTitles: ["Small", "Medium", "Extra Small"],
    title: "Variant",
    type: ControlType.Enum,
  },
  qVFnPYB39: {
    defaultValue: "Most popular",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  NjOVpa_TO: {
    defaultValue: true,
    title: "Highlighted",
    type: ControlType.Boolean,
  },
});
addFonts(
  FramerP8Lk6dtd8,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(fonts),
    ...getFontsFromSharedStyle(fonts3),
    ...getFontsFromSharedStyle(fonts2),
  ],
  {
    supportsExplicitInterCodegen: true,
  }
);
var __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerP8Lk6dtd8",
      slots: [],
      annotations: {
        framerVariables: '{"qVFnPYB39":"title","NjOVpa_TO":"highlighted"}',
        framerIntrinsicHeight: "24",
        framerIntrinsicWidth: "88",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"cDuHwnFRn":{"layout":["auto","fixed"]},"s_vZxnWn9":{"layout":["auto","fixed"]}}}',
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
      },
    },
    Props: {
      type: "tsType",
      annotations: {
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: {
      type: "variable",
    },
  },
};

// /:https://framerusercontent.com/modules/E6pMSS8bXVGPehZHnQ0c/YUWpZyAtqvKVVvBvkkET/WM8ej8Dha.js
var TagFonts = getFonts(stdin_default);
var TagWithOnClickWalletsg1yf6qWithMappedReactProps123mv8p =
  withMappedReactProps(
    withCodeBoundaryForOverrides(stdin_default, {
      nodeId: "MlGeSNB9_",
      override: withOnClickWallets,
      scopeId: "WM8ej8Dha",
    }),
    P8Lk6dtd8_exports
  );
var TagWithOnClickSocialAccountsp75y0eWithMappedReactProps123mv8p =
  withMappedReactProps(
    withCodeBoundaryForOverrides(stdin_default, {
      nodeId: "Fs4mW8Fqs",
      override: withOnClickSocialAccounts,
      scopeId: "WM8ej8Dha",
    }),
    P8Lk6dtd8_exports
  );
var cycleOrder2 = ["yJYekyzeg", "JdYsMmRvG", "flidXwDoM"];
var serializationHash2 = "framer-LP11u";
var variantClassNames2 = {
  flidXwDoM: "framer-v-1o42upa",
  JdYsMmRvG: "framer-v-cat25k",
  yJYekyzeg: "framer-v-rs3u4y",
};
function addPropertyOverrides2(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
var transition12 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: "spring",
};
var Transition2 = ({ value, children }) => {
  const config = React2.useContext(MotionConfigContext2);
  const transition = value ?? config.transition;
  const contextValue = React2.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  );
  return (
    <MotionConfigContext2.Provider value={contextValue}>
      {children}
    </MotionConfigContext2.Provider>
  );
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
  Default: "yJYekyzeg",
  Social: "flidXwDoM",
  Wallet: "JdYsMmRvG",
};
var getProps2 = ({ height, id, socialText, walletText, width, ...props }) => {
  return {
    ...props,
    JcSMHkHZg: walletText ?? props.JcSMHkHZg ?? "Wallets (3)",
    Ui8jM2lAf: socialText ?? props.Ui8jM2lAf ?? "Social accounts (1)",
    variant:
      humanReadableVariantMap2[props.variant] ?? props.variant ?? "yJYekyzeg",
  };
};
var createLayoutDependency2 = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
  const fallbackRef = useRef2(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React2.useId();
  const { activeLocale, setLocale } = useLocaleInfo2();
  const componentViewport = useComponentViewport2();
  const {
    style,
    className: className4,
    layoutId,
    variant,
    JcSMHkHZg,
    Ui8jM2lAf,
    ...restProps
  } = getProps2(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState2({
    cycleOrder: cycleOrder2,
    defaultVariant: "yJYekyzeg",
    ref: refBinding,
    variant,
    variantClassNames: variantClassNames2,
  });
  const layoutDependency = createLayoutDependency2(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
  return (
    <LayoutGroup2 id={layoutId ?? defaultLayoutId}>
      <Variants2 animate={variants} initial={false}>
        <Transition2 value={transition12}>
          <motion2.div
            {...restProps}
            {...gestureHandlers}
            className={cx2(
              scopingClassNames,
              "framer-rs3u4y",
              className4,
              classNames
            )}
            data-framer-name={"Default"}
            layoutDependency={layoutDependency}
            layoutId={"yJYekyzeg"}
            ref={refBinding}
            style={{
              ...style,
            }}
            {...addPropertyOverrides2(
              {
                flidXwDoM: {
                  "data-framer-name": "Social",
                },
                JdYsMmRvG: {
                  "data-framer-name": "Wallet",
                },
              },
              baseVariant,
              gestureVariant
            )}
          >
            <ComponentViewportProvider
              height={24}
              y={
                (componentViewport?.y || 0) +
                (0 + ((componentViewport?.height || 36) - 12 - 24) / 2)
              }
            >
              <SmartComponentScopedContainer
                className={"framer-g1yf6q-container"}
                layoutDependency={layoutDependency}
                layoutId={"MlGeSNB9_-container"}
                nodeId={"MlGeSNB9_"}
                rendersWithMotion={true}
                scopeId={"WM8ej8Dha"}
              >
                <TagWithOnClickWalletsg1yf6qWithMappedReactProps123mv8p
                  height={"100%"}
                  id={"MlGeSNB9_"}
                  layoutId={"MlGeSNB9_"}
                  NjOVpa_TO={true}
                  qVFnPYB39={JcSMHkHZg}
                  style={{
                    height: "100%",
                  }}
                  variant={"PkLBxMzqm"}
                  width={"100%"}
                  {...addPropertyOverrides2(
                    {
                      flidXwDoM: {
                        NjOVpa_TO: false,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                />
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
            <ComponentViewportProvider
              height={24}
              y={
                (componentViewport?.y || 0) +
                (0 + ((componentViewport?.height || 36) - 12 - 24) / 2)
              }
            >
              <SmartComponentScopedContainer
                className={"framer-p75y0e-container"}
                layoutDependency={layoutDependency}
                layoutId={"Fs4mW8Fqs-container"}
                nodeId={"Fs4mW8Fqs"}
                rendersWithMotion={true}
                scopeId={"WM8ej8Dha"}
              >
                <TagWithOnClickSocialAccountsp75y0eWithMappedReactProps123mv8p
                  height={"100%"}
                  id={"Fs4mW8Fqs"}
                  layoutId={"Fs4mW8Fqs"}
                  NjOVpa_TO={false}
                  qVFnPYB39={Ui8jM2lAf}
                  style={{
                    height: "100%",
                  }}
                  variant={"PkLBxMzqm"}
                  width={"100%"}
                  {...addPropertyOverrides2(
                    {
                      flidXwDoM: {
                        NjOVpa_TO: true,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                />
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
          </motion2.div>
        </Transition2>
      </Variants2>
    </LayoutGroup2>
  );
});
var css5 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-LP11u.framer-ql3eer, .framer-LP11u .framer-ql3eer { display: block; }",
  ".framer-LP11u.framer-rs3u4y { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px 0px 12px 0px; position: relative; width: 210px; }",
  ".framer-LP11u .framer-g1yf6q-container, .framer-LP11u .framer-p75y0e-container { flex: none; height: 24px; position: relative; width: auto; }",
];
var FramerWM8ej8Dha = withCSS2(Component2, css5, "framer-LP11u");
var stdin_default2 = FramerWM8ej8Dha;
FramerWM8ej8Dha.displayName = "ConnectionFilter";
FramerWM8ej8Dha.defaultProps = {
  height: 36,
  width: 210,
};
addPropertyControls2(FramerWM8ej8Dha, {
  variant: {
    options: ["yJYekyzeg", "JdYsMmRvG", "flidXwDoM"],
    optionTitles: ["Default", "Wallet", "Social"],
    title: "Variant",
    type: ControlType2.Enum,
  },
  JcSMHkHZg: {
    defaultValue: "Wallets (3)",
    displayTextArea: false,
    title: "walletText",
    type: ControlType2.String,
  },
  Ui8jM2lAf: {
    defaultValue: "Social accounts (1)",
    displayTextArea: false,
    title: "socialText",
    type: ControlType2.String,
  },
});
addFonts2(
  FramerWM8ej8Dha,
  [
    {
      explicitInter: true,
      fonts: [],
    },
    ...TagFonts,
  ],
  {
    supportsExplicitInterCodegen: true,
  }
);

// virtual:connection-filter
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
  Agq1L2jDe: {
    path: "/lib/careers/:slug",
  },
  DEi7PWhxw: {
    path: "/coming-soon",
  },
  J_r8CT7G7: {
    path: "/lib/about",
  },
  MiKvYzstd: {
    path: "/disconnect",
  },
  Mxb74mbpa: {
    path: "/verify-social",
  },
  OegBE_J9e: {
    path: "/lib/home",
  },
  SOf0RbDE_: {
    path: "/lib/blog",
  },
  TQDjkQC2A: {
    path: "/lib/contact",
  },
  UVAM5_4oX: {
    path: "/verify",
  },
  XanNBrFME: {
    path: "/kyc",
  },
  YBTUYW5mq: {
    path: "/lib/pricing",
  },
  a5CCfdDiy: {
    path: "/lib/updates/:slug",
  },
  augiA20Il: {
    path: "/",
  },
  cpP7I9WGp: {
    path: "/404",
  },
  e9YIc4Uv5: {
    path: "/lib/waitlist",
  },
  inNalAASs: {
    path: "/lib/blog/:slug",
  },
  ixIXvnG3U: {
    path: "/lib/legal/:slug",
  },
  nhNLVf3qq: {
    path: "/connections",
  },
  rX7FOhQc0: {
    path: "/lib/updates",
  },
  so5jTiDIE: {
    path: "/lib/careers",
  },
};

// virtual:connection-filter
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  base: "yJYekyzeg",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default2, {
        ...rest,
      })}
    </ContextProviders>
  );
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ConnectionFilterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "c32b11589f2bc68bdb1b6d8b6f1517c87e280d7db56dec1009246311f93861da"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default2}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  );
};
Object.assign(ComponentWithRoot, stdin_default2);
var connection_filter_default = ComponentWithRoot;
export { connection_filter_default as default };
